### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by vtorri** [google/brotli#1014]
latest release was out almost 3 years ago. Is a new release planned ?

**Comment by danfe** [comment]
Yes, new release would be nice!  Downstream maintainers are now trying to decide exactly [how to keep the package up-to-date](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=272005), and it would all be much easier if there's be freshly tagged version upstream.

**Comment by eustas** [comment]
Moved to #1056
