### ISSUE TITLE
UTF8 & co

### ISSUE THREAD

**Issue by fab1an2** [google/brotli#1015]
Please add to test UTF-8 and utf-16 example files

for example Polish lang: ĄĆŻŹĘŚŃŁÓ   ąćśężźółń

and some emoji

**Comment by eustas** [comment]
Sure, np. But what is the reason you are asking?

**Comment by fab1an2** [comment]
because I'm from Poland

**Comment by eustas** [comment]
The reason I've asked is that brotli operates with bytes and thus encoding- / codepage-agnostic... Well, almost. Static dictionary words are actually transformed as if they are UTF-8-like entities.

**Comment by eustas** [comment]
Done
