### ISSUE TITLE
Brotli wheel for arm64

### ISSUE THREAD

**Issue by special-character** [google/brotli#1016]
Tried installing brotli on an `arm64` mac and it doesn't seem to have a wheel.

ex:
```
#0 0.677 ERROR: Brotli-1.0.9-cp38-cp38-manylinux1_x86_64.whl is not a supported wheel on this platform.                                                                                                                                                                         
#0 0.717 Command exited with non-zero status 1
```

My env
```
Darwin MAC-BROBERTS 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64
```

Am I missing the wheel for arm64 or do we need to build one?

**Comment by anthrotype** [comment]
We do provide universal2 wheels for macos that should work on both x86_64 and arm64 platforms

See https://pypi.org/project/Brotli/#files

What python and pip version do you have?

**Comment by special-character** [comment]
Thanks for the extra info, I wonder what I am doing wrong 🤔

I am using python `3.11.3` and pip `23.1.2`. 

I do see those universal wheel files, I wonder why pip isn't trying to grab from there? Anyhoo, at least I know this *should* work. Going to dig some more.

**Comment by special-character** [comment]
Closing this issue because I was able to install the universal whl for brotli.
