### ISSUE TITLE
How to compress utf-16 string and decompress?

### ISSUE THREAD

**Issue by xeleoss** [google/brotli#1017]
Would love to have an example in the documentation for getting a compressed string and getting the original UTF-16 string (string in javascript).

**Comment by xeleoss** [comment]
Here is an example that I got, but I doubt its correctness:
```typescript
import { compress, decompress } from "brotli-compress";

function strToUint8Array(string: string) {
  const codeUnits = Uint16Array.from(
    { length: string.length },
    (element, index) => string.charCodeAt(index)
  );
  return new Uint8Array(codeUnits.buffer);
}

function uInt8ArrayToStr(bytes: Uint8Array) {
  const charCodes = new Uint16Array(bytes.buffer);

  let result = "";
  charCodes.forEach((char) => {
    result += String.fromCharCode(char);
  });
  return result;
}

export async function compressStr(str: string) {
  if (str.length === 0) {
    return "";
  }

  const bytes = strToUint8Array(str);
  const compressStr =  await compress(bytes);
  return uInt8ArrayToStr(compressStr);
}

export async function decompressStr(compressStr: string) {
  if (compressStr.length === 0) {
    return "";
  }

  const encodeBytes = strToUint8Array(compressStr);
  const decompressBytes = await decompress(encodeBytes);
  return uInt8ArrayToStr(
    decompressBytes
  );
}

```

**Comment by eustas** [comment]
"brotli-compress" is a third party module, so I can only guess.

Brotli compressor is byte-oriented, i.e. it takes `(U)Int8Array` for input and produces `(U)Int8Array` as output.

Indeed, internally JS stores strings as UTF-16, but there is no reason to compress UTF-16 data. Brotli does much better work in UTF-8.

Your code snippet looks well. Could you provide a sample that causes the error?

**Comment by xeleoss** [comment]
@eustas The error occurs if you run the following code:
```
const result = await compressStr("test test");
```

**Comment by eustas** [comment]
`uInt8ArrayToStr` at the end of `compressStr` should not be used. Result of compression is byte array. It can be even, it can be odd length. Moreover, JS is allowed to replace characters it does not understand with placeholders -> compressed data will be corrupted.

Fixed code is here: https://stackblitz.com/edit/node-5zrzir?file=index.js
