### ISSUE TITLE
mode_generic & dictionary sharing

### ISSUE THREAD

**Issue by AlexandrosEmvoliadis** [google/brotli#1020]
Hey

When brotli.MODE_GENERIC is set to compression mode, in my understanding, there is no static dictionary involved in the encoding process.

How does the decompressor decodes the received information? Do they still share the same dictionary?

**Comment by eustas** [comment]
Encoder and decoder have same "static" dictionary (see RFC).
Compression mode affects subtle internal compression params. There are 3 modes in API:

- `GENERIC` is default mode; if mode is not explicitly set, it is generic
- `TEXT` *should* be better mode for UTF-8 plaintext; currently it is same as generic
- `FONT` is a special mode for WOFF2 font payloads

Hopefully that answers your question.
