### ISSUE TITLE
Release v1.1

### ISSUE THREAD

**Issue by eustas** [google/brotli#1056]
This is an umbrella / checklist issue.

- [x] mark release candidate
- [x] actually release
- [ ] release Java package | see #715

**Comment by GitMensch** [comment]
@eustas wrote on January 3rd
>  Getting closer to it. Now working on the issues list and then we will have a release =)

If there are any show-stoppers found in the issue list then please add them to this list and drop a note once the list is considered to be complete.

Thank you.

**Comment by eustas** [comment]
Most likely we are going to land new features in parts. I.e. "raw dictionaries" first (v1.1) and serialized dictionaries later.
That would require some time for updating API in clean but non-breaking manner.
Thanks for patience.

**Comment by GitMensch** [comment]
The question is: Do we need even more features or can the current version be considered stable -> released, then get more features in future releases - even in the unlikely case that the next release after the "still-to-be-released" one is only 1 to 4 months away.

**Comment by eustas** [comment]
Exactly. The last comment was about cutting off (removing) non-stabilized feature for release (see https://github.com/google/brotli/blob/master/c/include/brotli/shared_dictionary.h#L39)

**Comment by GitMensch** [comment]
Will the 10 [open issues in the 1.1 milestone](https://github.com/google/brotli/labels/release-v1.1) be moved to another milestone?

**Comment by eustas** [comment]
Correct

**Comment by eustas** [comment]
Done. We hope to make next release rather soon, lets say after a month or two.

**Comment by diizzyy** [comment]
@eustas
Thanks for your time working on this projects!
Is it possible to generate a static source archive next release due to https://github.blog/2023-02-21-update-on-the-future-stability-of-source-code-archives-and-hashes/ which would help packagers a lot?

**Comment by eustas** [comment]
Sure, will do my best. Ideally you need to make a separate issue for that, so it do not fall of my radar. Thanks.

**Comment by diizzyy** [comment]
Thanks, tracked as https://github.com/google/brotli/issues/1076

**Comment by bric3** [comment]
Hello, any updates on getting the new Java artifacts on maven central ?

**Comment by slandelle** [comment]
@bric3 Are you aware of [Brotli4j](https://github.com/hyperxpro/Brotli4j)?

**Comment by bric3** [comment]
Hi @slandelle Yes I am. But Brotli 4J is using native libraries, which are not always compatible with the platform. Also, in the past, I remember having some issues integrating it with ktor (kotlin coroutine's based), maybe that has changed.

That said I would prefer to use the JVM based google code if possible.

**Comment by eustas** [comment]
Releasing Java moved to 1.1.1 (issue was fixed in wrapper code)

**Comment by GitMensch** [comment]
> Done. We hope to make next release rather soon, lets say after a month or two.

@eustas that sounds really nice - can you please create a meta-issue like this one for the next version (and possibly make it sticky so it is easily recognizable)?
