### ISSUE TITLE
bazel error no such package '@org_brotli//

### ISSUE THREAD

**Issue by ly0511** [google/brotli#1085]
I wrote a golang program and import "github.com/google/brotli/go/cbrotli". When I used bazel to compile the golang program, the following error occurred.
I don't know why and how to solve it
![image](https://github.com/google/brotli/assets/23255488/128a5a07-2da4-452a-9f07-fc2973586d99)

**Comment by eustas** [comment]
Will take a look soon

**Comment by eustas** [comment]
If you share a snippet of project that has this problem I'll try to tinker it. When it works we would be able to add the necessary steps to README.

**Comment by eustas** [comment]
Going to release v1.1.1 soon which could be published on BCR.
