### ISSUE TITLE
Brotli 1.1.0 changed return values?

### ISSUE THREAD

**Issue by kmilos** [google/brotli#1088]
See https://github.com/Exiv2/exiv2/issues/2762 and https://github.com/Exiv2/exiv2/pull/2763

**Comment by eustas** [comment]
Correct. Previous error descriptions were somewhat ugly.

**Comment by eustas** [comment]
See also CLI changes in https://github.com/google/brotli/commit/2e6164d7b0b7bdcb5d731bee6dd0f4e06708e006

**Comment by eustas** [comment]
In the given example "CL_SPACE" does not give any hint on what happened; now it says that this is error in the given input ("format" prefix).

**Comment by kmilos** [comment]
> In the given example "CL_SPACE" does not give any hint on what happened; now it says that this is error in the given input ("format" prefix).

Ta. I guess we'll just have to deal w/ both outputs somehow... 😞

**Comment by eustas** [comment]
Simply checking suffix should work...
