### ISSUE TITLE
[Feature Request] adding a option to control whether install the executable

### ISSUE THREAD

**Issue by leleliu008** [google/brotli#1090]
Hi, developers.
    Could we add a option (like `BROTLI_INSTALL_EXE`) to control whether install the executable? I only need a shared library and a static library, I don't need the exectuable. I'm a package manager, I do not use this project as a sub project.

**Comment by eustas** [comment]
Sure, why not. Will try to add it soon.

**Comment by timlegge** [comment]
@eustas in particular could the option not build the executable at all.  I am maintaining the perl module that links teh libraries.  However,  brotli.c uses fopen_s and sopen_s and older versions of gcc on windows do not support those functions.

However linking the libraries and testing the perl module works fine if I remove the build of the executable and the applicable tests from the CMakeLists.txt file

**Comment by leleliu008** [comment]
@eustas Thanks, I will try it when next release is published.
