### ISSUE TITLE
undefined symbol BrotliEncoderDestroyPreparedDictionary

### ISSUE THREAD

**Issue by 0x-2a** [google/brotli#1097]
After fresh pull and cmake of `1.1.0` am seeing a symbol lookup error for `BrotliEncoderDestroyPreparedDictionary`. Are there additional build args needed?

OS: Amazon Linux 2023
Arch: x86

```sh
wget https://github.com/google/brotli/archive/refs/tags/v1.1.0.tar.gz
tar -xvzf v1.1.0.tar.gz
cd brotli-1.1.0/

mkdir out && cd out
cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed ..
cmake --build . --config Release --target install

./install-files/bin/brotli --version
brotli 1.1.0
./install-files/bin/brotli: symbol lookup error: ./install-files/bin/brotli: undefined symbol: BrotliEncoderDestroyPreparedDictionary
```

**Comment by eustas** [comment]
Will check soon. Thanks for the heads-up.

**Comment by eustas** [comment]
The problem is that unless you really install `brotli`, you have to specify `LD_LIBRARY_PATH` to point to `./installed/lib`. Otherwise linked searches and finds system library does not contain mentioned symbol.

**Comment by 0x-2a** [comment]
Oh right, thanks!

**Comment by C-Collamar** [comment]
> The problem is that unless you really install `brotli`, you have to specify `LD_LIBRARY_PATH` to point to `./installed/lib`. Otherwise linked searches and finds system library does not contain mentioned symbol.

@eustas How can I "really install `brotli`"? Sorry, I'm new to this.

**Comment by C-Collamar** [comment]
I get it now. To fix this undefined symbol error by "really" installing `brotli`, I have to set `-DCMAKE_INSTALL_PREFIX` to a path where the system usually looks into.

```diff
- cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=./installed ..
+cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local .. 
```

So when I run Brotli as follows, the error goes away.

```bash
LD_LIBRARY_PATH=/usr/local/lib64 brotli --version
```

Now I only need to figure out how to run Brotli without specifying `LD_LIBRARY_PATH` everytime.

Thanks anyway!
