### ISSUE TITLE
Is brotli not supported on mac 14?

### ISSUE THREAD

**Issue by jasperdaiyile** [google/brotli#1135]
<img width="704" alt="image" src="https://github.com/google/brotli/assets/109211905/ec06e73e-0dce-48e8-94d8-4663474b052d">

**Comment by eustas** [comment]
That is more question to https://github.com/Homebrew/homebrew-core
But I'll take a look.

`:dunno` OSX version looks suspicious...

**Comment by eustas** [comment]
Work for me (14.3.1). Homebrew formulae states that there are bottles for `sonoma` and `arm64_sonoma`.

Please try `brew doctor`.

**Comment by eustas** [comment]
```
==> Reinstalling brotli 
==> Pouring brotli--1.1.0.arm64_sonoma.bottle.1.tar.gz
🍺  /opt/homebrew/Cellar/brotli/1.1.0: 24 files, 1013.4KB
```
