### ISSUE TITLE
No wheel for python 3.13

### ISSUE THREAD

**Issue by gut903826** [google/brotli#1208]
We upgraded to python 3.13 and there doesn't seem to have a wheel for it.

We got this error message: 
![Image](https://github.com/user-attachments/assets/91e6d252-ecec-469d-a71c-5ca4fe7c6de6)

As you can see on this page there is no file for python 3.13: https://pypi.org/project/Brotli/1.1.0/#files

**Comment by Sn1F3rt** [comment]
+1

**Comment by anthrotype** [comment]
thanks for the reminder, I'm working on this right now at https://github.com/google/brotli-wheels

**Comment by anthrotype** [comment]
Ok, the new wheels for python 3.13 should now have been uploaded to https://pypi.org/project/Brotli/1.1.0/#files

even though the CI for https://github.com/google/brotli-wheels/releases/tag/v1.1.0-py313 says it failed:
https://github.com/google/brotli-wheels/actions/runs/11403349952/job/31731456149

twine actually managed to upload all the wheels (skipping those that were already present for v1.1.0). It's only the source distribution tar.gz that make the whole command error. But that one didn't change.

Whenever a new upstream brotli release is made, the brotli-wheels repo can sync with that and build new wheels for all pythons, not just 3.13.

So I think this can be closed now.

**Comment by Sn1F3rt** [comment]
Thanks!
