### ISSUE TITLE
How to compress/decompress a small message with a shared dictionary?

### ISSUE THREAD

**Issue by pkolaczk** [google/brotli#1213]
I can see only the function `BrotliEncoderCompressStream` can use a shared dictionary (need to attach it first), but one-shot compression/decompression functions like `BrotliEncoderCompress` and `BrotliDecoderDecompress` can't. 

What is the recommended way to compress/decompress a series of small (a few kB each), independent messages?

**Comment by eustas** [comment]
`BrotliEncoderCompress` and `BrotliDecoderDecompress` in an API mistake, we don't recommend using them (except for simplest testing code).

Recommended way to use streaming API. If dictionary does not change, it is recommended to prepare dictionary once and reuse prepared instance for encoding.
