### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [google/brotli#152]
Would you like to add more error handling for return values from functions like the following?
- [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html "Reposition a file-position indicator in a stream.") ⇒ [FileSize](https://github.com/google/brotli/blob/7f7a2fb48cec63c0459ec6b6e7260810bfb01819/tools/bro.cc#L160)
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [BrotliFileIn constructor](https://github.com/google/brotli/blob/55a40ce214be844b8860ef46e3ba321324542679/enc/streams.cc#L90)

**Comment by eustas** [comment]
Fixed. Thank you!

**Comment by elfring** [comment]
To which commits do you refer to for this issue?

**Comment by eustas** [comment]
https://github.com/google/brotli/pull/209

**Comment by elfring** [comment]
Are there [any update candidates](https://github.com/google/brotli/blob/c85bb508cb86eaac98a4667e67e944018f5abbf2/tools/bro.cc#L185 "More exception handling?") left over?

**Comment by eustas** [comment]
This one looks safe, since we haven't touched the file contents.
Will fix it soon.

**Comment by szabadka** [comment]
Fixed in PR #235

**Comment by elfring** [comment]
Thanks for another small source code improvement.
