### ISSUE TITLE
memmove16 implementation is playing with fire

### ISSUE THREAD

**Issue by rygorous** [google/brotli#159]
As already noted in the code https://github.com/google/brotli/blob/master/dec/decode.c#L89, assuming details about the memcpy implementation and optimizations is playing with fire. Maybe introduce a BROTLI_NO_DANGEROUS_OPTIMIZATIONS #define that avoids this kind of code path, to ease porting to non-mainstream architectures?

**Comment by eustas** [comment]
Fixed with PR 183.
Compiling with -DBROTLI_BUILD_PORTABLE avoids overlapping memcpy and unaligned reads.
