### ISSUE TITLE
list file  support

### ISSUE THREAD

**Issue by bunnyblue** [google/brotli#161]
brotli can't  list file in archive?

**Comment by nemequ** [comment]
Brotli is at the wrong level for that.  It just compresses a stream of data, it has no knowledge about what is inside.  Think gzip, bzip2, or xz.

To compress multiple files you would generally tar them up then pass that to the compressor.  If you want things like random access, file listing, etc., you would need to create an archive format or extend an existing one to support brotli compression (just like zip files support deflate).  To do that you would basically just put multiple streams in a file; the Wikipedia article on [Zip's design](https://en.wikipedia.org/wiki/Zip_%28file_format%29#Design) should give you a basic idea of what is involved.

**Comment by bunnyblue** [comment]
thank you
