### ISSUE TITLE
Proper build system

### ISSUE THREAD

**Issue by fxfactorial** [google/brotli#162]
Can you guys use a proper build system, cmake or even a plain makefile? 

At least so that we can get a single .so/.dylib and be able to easily link against it via `-lbrotli` or something.

**Comment by nuch-lek** [comment]
เมื่อ วันพุธที่ 23 กันยายน ค.ศ. 2015, Edgar Aroutiounian <
notifications@github.com> เขียนว่า:

**Comment by bagder** [comment]
I've started a little attempt at build scripts and setup to build a library (.so and .a with libtool) from the brotli source code here: https://github.com/bagder/libbrotli

Builds a decoder lib right now.

**Comment by fxfactorial** [comment]
@bagder Nice thanks, is it feasible to eventually have just one library instead of separate ones for encoder, decoder?

**Comment by bagder** [comment]
Oh certainly. This is just starting so I'm interested in feedback and improvements. I simply started with the decoder parts because that where my primary interest lies.

**Comment by nuch-lek** [comment]
VID_20150927_014307.mp4
<https://drive.google.com/file/d/1dAVtiGs0KV8nUr6lSCj80bWw2MT2-WxksA/view?usp=drivesdk>

VID_20150927_014305.mp4
<https://drive.google.com/file/d/1ntKHY9Yhql6vD0GZ_eIvXyQbG_Ayueh4Sg/view?usp=drivesdk>




-- 
ส่งจาก Gmail มือถือ

**Comment by aa88088aa** [comment]
你傳什麼?我要密碼
2015/9/30 下午9:46於 "nuch-lek" <notifications@github.com>寫道：

**Comment by CoolOppo** [comment]
@aa88088aa I think you may have accidentally replied to the wrong issue or something.

**Comment by aa88088aa** [comment]
I lost my password , demanding to know the password ? Know what I mean?
2015/10/1 上午6:43於 "CoolOppo" <notifications@github.com>寫道：

**Comment by CoolOppo** [comment]
i really have no idea what you mean

**Comment by Kirkis** [comment]
Actually, there seems to be makefiles inside each folder (dec, enc, tools). To build everything, cd to "tools" then "make".
Or am I mistaken?
Doesn't have the "install" procedure though.
