### ISSUE TITLE
Suggestion: Include installation instructions in the README.

### ISSUE THREAD

**Issue by sbrl** [google/brotli#166]
Including installation / setup / usage instructions in the README would allow more people to download / use / test brotli more easily.

**Comment by wbond** [comment]
It should note that the project uses c++11, and thus requires GCC 4.7+, according to the discussion at #158.

**Comment by fred-wang** [comment]
@eustas Also, the README should really explain the different build systems (CMake, python, Bazel, make, premake) and explain how to build and install shared libraries & headers with CMake (for package maintainers, expecially).

**Comment by sbrl** [comment]
Thanks :D
