### ISSUE TITLE
Is there a way to create a custom dictionary?

### ISSUE THREAD

**Issue by DiThi** [google/brotli#168]
Most files of our project have data that is not text, but delta-encoded floats and shorts, and I think it would greatly benefit from creating a dictionary with the most common strings.

Related #165

**Comment by wizzard0** [comment]
:+1:

**Comment by eustas** [comment]
Use BrotliCompressWithCustomDictionary / BrotliSetCustomDictionary API

**Comment by DiThi** [comment]
@eustas Thanks!

Though, I can't find any documentation or examples. Can the custom dictionary be anything? Is it enough to concatenate a bunch of common data together?

**Comment by eustas** [comment]
Custom dictionary could contain any data. Like with any LZ codec it is used as an initial window data.
Though I could recommend not to place short pattern last few bytes of custom dictionary, because it  may be the "blind" zone of encoder.

**Comment by yangxiaomin08** [comment]
Asking the same question, is there any tool that could help to generate custom dictionary for specified domain?

**Comment by eustas** [comment]
You could try this: https://github.com/vkrasnov/dictator
