### ISSUE TITLE
Particular file are not identical after compression and decompression with quality 1

### ISSUE THREAD

**Issue by tesseract2048** [google/brotli#169]
I have a random generated file: https://drive.google.com/file/d/0By7bqJ83IOI8WUU5T2xXTzhqMjA/view?usp=sharing

Length of the file is 8192000.
Compress it with: `bro --quality 1 --input bro_sample_0 --output bro_sample_0.bro`
Then decompress with: `bro --decompress --input bro_sample_0.bro --output bro_sample_0.1`
And I got a file with length 20774912, which does not make sense.

**Comment by eustas** [comment]
We've found the problem. The fix will be rolled soon.

**Comment by eustas** [comment]
This should be fixed now (https://github.com/google/brotli/pull/164)

**Comment by tesseract2048** [comment]
Verified, thanks.
