### ISSUE TITLE
Crashing with std::bad_alloc

### ISSUE THREAD

**Issue by maximecaron** [google/brotli#173]
I was trying to compress a 30GB sqlite file with data from wikipedia on a machine with 1GB of memory.
And the command crash with std::bad_alloc on quality 11, 10 and 9.

Command was running on Debian 8.1 x64 compiled with G++ 4.9.2

**Comment by eustas** [comment]
Could you share a link to the db file, please.

I've experimented with file that contains 32 copies on enwik9 and memory usage peak is 332M...

**Comment by eustas** [comment]
Should be fixed on v0.5.
Please check. If problem is still there, feel free to reopen the issue.
