### ISSUE TITLE
golang support

### ISSUE THREAD

**Issue by hnsl** [google/brotli#182]
It would be nice to have some wrapper or native implementation for golang.

**Comment by gyf19** [comment]
+1

**Comment by fxfactorial** [comment]
You could always write one, the code is not that bad and you can take inspiration from the their python bindings, or my OCaml bindings, https://github.com/fxfactorial/ocaml-brotli/blob/master/src/brotli_stubs.c#L41 and there was a Lua binding available as well.

**Comment by maximecaron** [comment]
+1

**Comment by beauhoyt** [comment]
+1

**Comment by kothar** [comment]
I've implemented a very limited binding for the BrotliCompressBlock and BrotliDecompressBlock functions. Stream bindings shouldn't be hard, but not sure when I will get to them, so I'd welcome anyone else's contributions in that area.

https://github.com/kothar/brotli-go

**Comment by dsnet** [comment]
And here's another Go Brotli package: https://github.com/dsnet/compress

This is written in pure Go, but only implements the decoder for the time being.

**Comment by gyf19** [comment]
Cool

**Comment by anurag** [comment]
https://github.com/andybalholm/brotli is a pure Go encoder and decoder.
