### ISSUE TITLE
Python binding: add streaming compression / decompression support.

### ISSUE THREAD

**Issue by rpasta42** [google/brotli#191]
I'm trying to implement streaming compression using brotli. There's very little documentation and I haven't found anyone else trying to accomplish same thing. I assume I need to specify lgwin to set the block size, but when I run this code it gives me an error "brotli.error: BrotliDecompress failed"

my_str = 'very long string blah blah blah'
a = brotli.compress(my_str, lgwin=16)
b = brotli.decompress(a[0:16])

Am I doing something wrong or did I misunderstand the purpose of the lgwin parameter?

**Comment by eustas** [comment]
Currently python brotli module doesn't support streaming compression/decompression.
lgwin is a parameter that is used to specify the length of LZ77 sliding window size.

Of course, streaming support will be eventually added to the Python bindings,... So stay tuned.

**Comment by Kijewski** [comment]
> Of course, streaming support will be eventually added to the Python bindings,... So stay tuned.

Do you have a more precise ETA by now? More precise than "eventually" I mean.

**Comment by KostyaKow** [comment]
I know C++ and Python, but have no familiarity with brotli codebase.

Where would I begin if I wanted to implement the Python binding for this?

**Comment by thedrow** [comment]
Looks like this is complete. Should we close this issue?
