### ISSUE TITLE
License of paper

### ISSUE THREAD

**Issue by jeroenooms** [google/brotli#192]
What is the license of the paper [Comparison of Brotli, Deflate, Zopfli, LZMA, LZHAM and Bzip2 Compression Algorithms](http://www.gstatic.com/b/brotlidocs/brotli-2015-09-22.pdf)? Can I freely distribute this document?

**Comment by szabadka** [comment]
We added the paper to the docs/ directory in PR #198, so you can use it with the same licence as the rest of the project.

**Comment by jeroenooms** [comment]
Thank you.
