### ISSUE TITLE
UBSAN misaligned address errors

### ISSUE THREAD

**Issue by jeroenooms** [google/brotli#203]
See http://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/brotli-Ex.Rout

**Comment by eustas** [comment]
Try to compile with -DBROTLI_BUILD_PORTABLE option

**Comment by jeroenooms** [comment]
Thanks. Not sure if that justifies undefined behavior in the default build though.

**Comment by eustas** [comment]
We focused mostly on x64 and ARMv7 where unaligned read doesn't cause undefined behaviour (except for atomicity, but it's not the case).
We will consider to turn this optimisation only when compiler detects compatible CPU architecture.

**Comment by jeroenooms** [comment]
I think you are mistaken, these UBSAN errors appear on linux on `x86_64`.

**Comment by eustas** [comment]
Yes, ubsan reports errors on x86_64 and we used it to check "portable" version.
But reporting unaligned reads by ubsan on x86_64 is done intentionally, so developers could verify their product without compiling for / running on specific hardware that can't to unaligned reads.
