### ISSUE TITLE
woff2_decompress always uses .ttf extension for the output file

### ISSUE THREAD

**Issue by miguelsousa** [google/brotli#213]
`woff2_decompress` always uses `.ttf` extension for the output file, even if the payload is an OTTO font.
You can test with [Source Sans Pro](https://github.com/adobe-fonts/source-sans-pro/tree/release/WOFF2).

**Comment by khaledhosny** [comment]
I think you meant to report this too https://github.com/google/woff2/?

**Comment by miguelsousa** [comment]
You're right. Sorry about that.
