### ISSUE TITLE
Clarify unordered_map file warning 

### ISSUE THREAD

**Issue by kennethormandy** [google/brotli#22]
I was trying to use google/woff2 on a machine running OS X 10.8 and got the following error:

```sh
./brotli/enc/./static_dict.h:21:10: fatal error: 'unordered_map' file not found
```

It turns out that the version of gcc with Xcode 5 is too low, I had to upgrade it manually from 4.2 to 4.7. If it’s relatively easy to clarify what that error message is about, I think it could be helpful. To be fair, I don’t really know anything about this stuff though, so feel free to disregard as well.

Thanks!

**Comment by CFXd** [comment]
@kennethormandy, mind sharing the best way you fond to upgrade Xcode's gcc? So many tuts out there it's hard to tell the good from the bad...

**Comment by Psiablo** [comment]
Might be relevant. I was getting this same error and fixed the issue with adding some additional flags on build. See starting line 37. https://github.com/Psiablo/ttf2woff2/blob/91b55b30683f011ca415ee8e24a55228dc4fd834/binding.gyp

**Comment by szabadka** [comment]
The encoder does not use unordered_map any more.
