### ISSUE TITLE
Trademarks in dictionary

### ISSUE THREAD

**Issue by rotfllol** [google/brotli#220]
There are trademarks in the dictionary:

* Windows
* Google
* google
* apple

Do you need written consent from the trademark owners before being able to use brotli?

**Comment by csvan** [comment]
Did you honestly create a GH account just to troll in light of the recent file extension controversy?

**Comment by jyrkialakuijala** [comment]
It is not a human readable document, and does not affect brotli's ability to produce or not to produce any strings.
