### ISSUE TITLE
static kBitCostThreshold affects compression ratio

### ISSUE THREAD

**Issue by tesseract2048** [google/brotli#221]
`encode.cc`:392
```
      static const int kSampleRate = 13;
      static const double kMinEntropy = 7.92;
      static const double kBitCostThreshold = bytes * kMinEntropy / kSampleRate;
```
kBitCostThreshold is cached once initialized. 
However, if brotli library is reused within the same process, first compress a small piece of data, then a large one will suffer from poor compression ratio, since some block will be misleadingly uncompressed.

**Comment by szabadka** [comment]
Thank you for reporting this issue. This was fixed in PR #223.
