### ISSUE TITLE
Compression ratio is better after tweaking quality 6 -> 1 for big files

### ISSUE THREAD

**Issue by tesseract2048** [google/brotli#222]
I have a ~30GB text file filled with ascii numbers.
If I truncate to first 1GB, brotli outperforms gzip in size about ~20%.
However, if I compress the whole file with quality 1, brotli compressed file is only 8% smaller.
More strange, if I compress the whole file with quality 6, brotli compressed file is actually 11% bigger than gzip.

Any theory what is going on? Thanks.

**Comment by tesseract2048** [comment]
Tested on a 2.79GB file, results are same.

**Comment by jyrkialakuijala** [comment]
Are these sorted 64-bit hashes?

**Comment by tesseract2048** [comment]
Yes, you can say that, @jyrkialakuijala.
It represents sparse feature.

**Comment by jyrkialakuijala** [comment]
I have identified a problem in the hashing that degrades the compression performance after 2 GB for quality >= 5. We will fix this within three days.

**Comment by tesseract2048** [comment]
Sure, thanks.
I've identified that it worked as expected with quality <= 4.

**Comment by jyrkialakuijala** [comment]
Levels 5-9 should work in the head now. Level 11, the same as 10, is still misbehaving for files longer than 2 GB.

**Comment by eustas** [comment]
As mentioned in previous comment, should be fixed now.
If not, feel free to reopen the issue.
