### ISSUE TITLE
Warnings on mingw-w64

### ISSUE THREAD

**Issue by jeroenooms** [google/brotli#267]
Compiling with gcc 4.6.3 / mingw-w64: http://pastebin.com/raw.php?i=9pTWA0DA

**Comment by eustas** [comment]
Thank you for your report. We are actively working on those warnings...

**Comment by jeroenooms** [comment]
Update: most of these are now fixed, but a few remain. Here the new log: http://pastebin.com/raw.php?i=p74N5zkM

**Comment by jeroenooms** [comment]
Update: only one warning remains:

```
enc/encode.cc -o enc/encode.o
enc/encode.cc: In member function 'bool brotli::BrotliCompressor::WriteBrotliData(bool, bool, size_t*, uint8_t**)':
enc/encode.cc:409:41: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

**Comment by jeroenooms** [comment]
Closing in favor of https://github.com/google/brotli/issues/302.
