### ISSUE TITLE
Streamable output from the decoder

### ISSUE THREAD

**Issue by KenjiBaheux** [google/brotli#27]
From https://code.google.com/p/chromium/issues/detail?id=452335 where we are exploring how to support brotli as an HTTP transfer-encoding method

Comment Nb. 20:
"Chrome's networking stack is a single thread event loop. To prevent arbitrary data from being buffered in memory, and to get data to consumers as fast as possible, this will need to be rewritten in a way for the caller to call it repeatedly to get the data out of it."

**Comment by szabadka** [comment]
#79 added streaming output support.
