### ISSUE TITLE
Performance measurements and feedback

### ISSUE THREAD

**Issue by nitram509** [google/brotli#273]
### About

I'm working on a project called [jbrotli](https://github.com/nitram509/jbrotli) to make Brotli compression available to Java developers.
My goal is to enable Java based HTTP server to use Brotli compression on the fly.

I've did some performance benchmarks with the cp.html (from canterbury corpus).
It turns out, that gzip is little more than twice as fast as brotli, when compressing this HTML.
This fails may expectations - I thought the Brotli outnumbers gzip.
### Issue

Most other benchmarks make Brotli shine, compared to gzip.
I'm looking forward to get feedback from the experts,
why these numbers are so "bad" - or where the code could be improved.
### Testcases

All these test cases use a) the 24kB HTML from canterbury corpus and b) 2xcp.html, all read from memory.
##### brotli_compression_with_BrotliCompressor_using_ByteBuffer

uses brotli::BrotliCompressBuffer()
Intended to use simple stateless interface of brotli.
Second, it also is intended to show differences between byte[] and direct ByteBuffer in Java.
Remark: Most likely this direct ByteBuffer thingy is faster than using byte[], as many other projects already experienced that. For comparison to brotli - this can be treated equal to using byte[]
- brotli quality parameter = 5

source https://github.com/nitram509/jbrotli/blob/master/jbrotli-native/src/main/cpp/de_bitkings_jbrotli_BrotliCompressor.cxx
##### brotli_compression_with_BrotliStreamCompressor_using_byte_array

Instantiates only one object of brotli::BrotliCompressor
and only does CopyInputToRingBuffer() followed by WriteBrotliData().
Intended to have pure compression and reuse of the pre-calculated dictionary.
- brotli quality parameter = 5

source https://github.com/nitram509/jbrotli/blob/master/jbrotli-native/src/main/cpp/de_bitkings_jbrotli_BrotliStreamCompressor.cxx
##### gzip_compression

Uses default GZIPOutputStream with default compression level.
- compression level default (expect 5 or 6)
##### JNI_doing_simple_memcpy_using_byte_array

This test uses the same Java method signature as the compressor, but only does 'memcpy'.
This is intended to show how much overhead ther is for doing JNI calls.
### Results

```
## using cp.html 24kB HTML
Benchmark                                                         Mode  Cnt       Score      Error  Units
brotli_compression_with_BrotliCompressor_using_ByteBuffer        thrpt    5          65 ±        2  ops/s
brotli_compression_with_BrotliStreamCompressor_using_byte_array  thrpt    5         761 ±        6  ops/s
gzip_compression                                                 thrpt    5        1992 ±       47  ops/s
JNI_doing_simple_memcpy_using_byte_array                         thrpt    5      837511 ±     4273  ops/s

## using 2xcp.html 48kB HTML
Benchmark                                                         Mode  Cnt       Score      Error  Units
brotli_compression_with_BrotliCompressor_using_ByteBuffer        thrpt    5          60 ±        0  ops/s
brotli_compression_with_BrotliStreamCompressor_using_byte_array  thrpt    5         384 ±       58  ops/s
gzip_compression                                                 thrpt    5        1613 ±       52  ops/s
JNI_doing_simple_memcpy_using_byte_array                         thrpt    5      461217 ±     2856  ops/s
```
### Setup:
- using brotli 0.2.0 release
- using Visual Studio 2010 compiler 64bit
- using custom cmake file (maybe some compiler options are missing)
- using Java Micro Benchmark (jmh) for measurement
- using Java 1.8.0_u65, 64bit
- source https://github.com/nitram509/jbrotli   ... consider _experimental_ ;-)

**Comment by nemequ** [comment]
> It turns out, that gzip is little more than twice as fast as brotli, when compressing this HTML.
> This fails may expectations - I thought the Brotli outnumbers gzip.

Brotli is generally slower than gzip for compression.  It is usually a bit faster at **de**compression, and the compression ratio is much higher.  See https://quixdb.github.io/squash-benchmark/?dataset=cp.html&machine=peltast&visible-plugins=brotli,zlib#ratio-vs-decompression for results for cp.html; results are probably similar for most datasets.  If you turn on some of the other codecs squash offers (click the label in the legend) you'll get a more complete picture of where brotli fits in with the competition.

This is a pretty good place for brotli to be.  Compressing content once and decompressing many times is a pretty common use case, so it's usually better to emphasize decompressor speed and ratio at the expense of compressor speed.

**Comment by powturbo** [comment]
you might need or be interested in [TurboBench](https://github.com/powturbo/TurboBench).
You can make your own benchmarks, with your data.

**Comment by eustas** [comment]
Added benchmarks section to README.md

**Comment by eustas** [comment]
We are working on our own Java wrappers. Soon it will be possible to make measurements and compare results / investigate bottlenecks.

**Comment by nitram509** [comment]
Wow cool, that you plan to provide Java wrappers. I'm interested in your outcomes.
So we might join forces and can further improve brotli support in the Java World.

**Comment by chrisco484** [comment]
@nemequ 
"Compressing content once and decompressing many times is a pretty common use case,"

Maybe back in the static HTML days but nowadays with the dynamic HTML generation provided every Java UI framework in a data driven website precompressing once and reusing compressed versions of the HTML just doesn't really work well unless you add a serious amount of code to work out everything that could change on a page (content, user permissions, available JS powered AJAX2 controls etc.,) and when something does change blow away the cached compressed version of the HTML and recompress.

**Comment by eustas** [comment]
Hello, Martin.

Now, we have our JNI wrappers published. Could you test their performance, and see if the problem is still here.

Thanks in advance,
  Eugene.

**Comment by eustas** [comment]
Ping?

Feel free to reopen...
