### ISSUE TITLE
Feature Request: Resumable stream compression/decompression

### ISSUE THREAD

**Issue by YLivay** [google/brotli#276]
Hey!

Brotli's compression ratio and decompression speed makes it a very viable candidate for serving pre-compressed files to decompress on the fly as they are downloading. For big files its common to offer resumable downloads, but with stream decompression its impossible to use without restoring the stream decoder's context at the time it was stopped.

Is it possible add a function to the API to serialize the stream's context and resume it later?

Excuse me if I'm talking nonsense, I'm unfamiliar with the grits of Brotli's implementation :)

**Comment by eustas** [comment]
Hello.

Serialized context may take up to 16 megabytes (the size of the window),...
Could you point to other compressors that have such API, please.
It will help us understand the best practices in the field...

Best regards,
  Eugene.
