### ISSUE TITLE
BrotliDecompressBufferStreaming (/ BrotliDecompressStream) setting available_in to 1

### ISSUE THREAD

**Issue by mbevin** [google/brotli#285]
Using brotli from master, sometime when I call BrotliDecompressBufferStreaming (/ BrotliDecompressStream), it sets available_in to 1. This is happening while the result code is BROTLI_RESULT_SUCCESS, so according to the documentation comment, this shouldn't be possible., and it's not clear if+how I should deal with this, since it appears to be a bug I'm guessing I can't make any assumptions as to there being any way to recover from this?

This didn't occur with a month-or-so older master brotli, but that had other issues (BrotliDecompressBufferStreaming always returning huge 4mb chunk sizes)

**Comment by eustas** [comment]
Going to check/fix it soon. And update documentation as well.

**Comment by eustas** [comment]
Can not reproduce.
Could you attach sample compressed file, please?
