### ISSUE TITLE
Undefined behaviour in python .cc module?

### ISSUE THREAD

**Issue by mmastrac** [google/brotli#286]
When compiling on OSX, I get this:

    python/brotlimodule.cc:131:12: warning: comparison of constant -1 with expression of type 'BrotliParams::Mode' is always true
          [-Wtautological-constant-out-of-range-compare]

I suspect the cast of the out-of-range -1 to an enum is undefined behaviour in C++, but I'm not certain.

**Comment by anthrotype** [comment]
cc @khaledhosny

**Comment by eustas** [comment]
Hello, Matt.

 Thank you for your report. Could you check if casting mote to int in python/brotlimodule.cc:131 fixes the problem?

Best regards,
  Eugene.
