### ISSUE TITLE
Standardize some magic bytes to identify a brotli stream

### ISSUE THREAD

**Issue by jrmuizel** [google/brotli#298]
This would be very useful for dealing with something like .tar.br fies.

**Comment by eustas** [comment]
Unfortunately, there is no magic bytes for brotli.
In future brotli streams will be wrapped in some framing format which will have magic bytes that could be used to identify it.

**Comment by eustas** [comment]
Mark Adler helped us much with proof-testing brotli and refining specification.
Here is his framing format proposal:
https://github.com/madler/brotli/blob/master/br-format-v3.txt

>Signature in hexadecimal (four bytes):
>
>ce b2 cf 81

**Comment by catlee** [comment]
That's very helpful, thank you!

Do you have any idea when the new framing could be introduced? And how to transition content and clients over to the new format?

**Comment by dsnet** [comment]
Is there a process through which people are peer reviewing how the new framing format is being designed?

Has any thought been given to possibly re-using a "framing" format like the [XZ file format](http://tukaani.org/xz/xz-file-format-1.0.4.txt) where brotli is just one of the filter chains that can be used?

**Comment by jason-sachs** [comment]
This issue was closed in Oct 2016. What was the resolution?

**Comment by pavelloz** [comment]
Im also interested in detecting brotli archives in an easy and convenient way.

**Comment by matijaskala** [comment]
I've written a [wrapper program](https://github.com/matijaskala/brzip.parallel) around brotli and have been using it locally on my system for quite some time

**Comment by simonmittag** [comment]
has this ever been implemented? identifying binary streams without relying on external headers (HTTP) is commonplace functionality

**Comment by ross-spencer** [comment]
Looking around (and testing this locally) there doesn't seem to be any resolution, yet multiple workflows rely on basic magic capability, my own use case, digital preservation and archiving where we need to identify file formats and understand their intellectual payload. 

Can this issue be reopened?
