### ISSUE TITLE
There is no good way to estimate the size of out when decompressing

### ISSUE THREAD

**Issue by mshneer** [google/brotli#335]
I am using BrotliDecompressBufferStreaming which does not provide a way to determine required size for output buffer. For large outputs, I am receiving BROTLI_RESULT_NEEDS_MORE_OUTPUT and the only solution I could work so far is to blindly increase the size of the output buffer and retry.

Possible ways to address these shortcomings.
1. when BROTLI_RESULT_NEEDS_MORE_OUTPUT is returned, available_in would contain the size of the required buffer.
2. Even better solution, that would avoid memory fragmentation, is to allow the caller placing output into chained buffers. I.e. available_in could return the size of the input  buffer processed so far. In this case, one could create new buffer in a loop until available_in does not drop to 0.

**Comment by danielrh** [comment]
I generally encode the output size in a header on my branch here
https://github.com/danielrh/brotli/tree/header

it's also good to have a magic number and the commit ID of the binary that encoded it

**Comment by eustas** [comment]
There is [BrotliDecompressedSize](https://github.com/google/brotli/blob/master/dec/decode.h#L46) method.
Unfortunately, it works only is stream contains only one block. But it is the most frequent case.
We plan to add framing format in future, but currently you need to attach your own header, as Daniel said.
