### ISSUE TITLE
Negative array access on state->mtf for InverseMoveToFrontTransform

### ISSUE THREAD

**Issue by danielrh** [google/brotli#337]
When decoding quickfox_repeated.compressed
The local variable `index` can start off zero, which will result in an access to s.mtf[-1]
https://github.com/google/brotli/blob/master/dec/decode.c#L881

Since the previous variable in the struct is a 32 bit integer mtf_upper_bound, and usually little endian < 2^24, this generally results in a zero access.

I believe this could exhibit itself as an issue on big endian systems and could be undefined behavior nevertheless. I think it would be more intuitive to restructure the code to avoid out of bounds access.

**Comment by eustas** [comment]
Hello, Daniel.

  Thank you for your report. Actually, the value taken from negative index lives very shortly - it is overwritten by mtf[0] = value. Nevertheless, going to fix it soon.

**Comment by eustas** [comment]
Fixed in PR #343
