### ISSUE TITLE
crash inside brotli::BrotliCompressor::WriteBrotliData()

### ISSUE THREAD

**Issue by nitram509** [google/brotli#346]
## Abstract 
When doing compression, using the WriteBrotliData() 3-times in a row, the program will crash.

Hint:
the argument for 'is_last' is always 'true'. Setting this argument to false, will "fix" this crash.

### Expected behavior
Even if I use is_last=true multiple times, I expect no crashes.
Instances of BrotliCompressor should maintain a "safe" internal state
and should not crash.

## Example program, which crashes:
https://gist.github.com/nitram509/081b5826e173910eba20097cba9dde8c

## Environment
The program crashes on these environments
* Windows 10, 64bit, MinGW-w64 v3.4, GCC v4.9.2
* Windows 10, 64bit, Visual C++ 2015 Update v2
* Ubuntu Linux, 64bit, GCC v4.9.2-10

The program will NOT crash on OSX, even when doing 100x WriteBrotliData().
* OSX (latest), 64bit, LLVM v7.3.0, clang-703.0.31

## Background information
I'm the author of jbrotli (Java bindings for (lib-)brotli).
A user of jbrotli filled an issue and it seems to me, there is a bug inside brotli itself.
So I wrote a minimal C-program to demonstrate, what's going on inside the Java-program.

**Comment by eustas** [comment]
Hello.

  Thank you for your report. Going to fix problem ASAP.
  Meanwhile we're preparing update to encoder that will bring more clear C streaming API.

Best regards,
  Eugene.

**Comment by nitram509** [comment]
:+1:
