### ISSUE TITLE
FastLog2 constant improvement

### ISSUE THREAD

**Issue by mikir** [google/brotli#353]
In the header fast_log.h, the following constant is used:

`static const double kLog2Inv = 1.4426950408889634f;`

Please, consider to replace this constant with exact formula not to loose accuracy:

`static const double kLog2Inv = 1.0f / log(2);`

**Comment by eustas** [comment]
Constant already has too high prescision.
When either of kLog2Inv values is printed out the result is 1.4426950*2162933349609*

**Comment by jyrkialakuijala** [comment]
perhaps removing the f from the end would change something on another compiler?

**Comment by eustas** [comment]
Fixed in v0.5
NB: most frequently used values are looked up in table. High precision for bigger values is not required.
