### ISSUE TITLE
.python-eggs

### ISSUE THREAD

**Issue by pdknsk** [google/brotli#354]
``` Python
# Python
import brotli
```

Is there a reason it makes these in `$HOME`? I've yet to notice a `pip` installed package do this.

``` Bash
$ ls -R .python-eggs/
.python-eggs/:
Brotli-0.3.0-py2.7-linux-x86_64.egg-tmp

.python-eggs/Brotli-0.3.0-py2.7-linux-x86_64.egg-tmp:
brotli.so
```

**Comment by anthrotype** [comment]
http://stackoverflow.com/questions/2192323/what-is-the-python-egg-cache-python-egg-cache

I'd recommend you don't do 
    python setup.py install
when installing from the source directory, as that triggers setuptools to create an .egg. Instead, use
    pip install .
This will not create eggs, but will install the package unzipped in the site-packages.

**Comment by pdknsk** [comment]
Thanks for the tip. This should be in the documentation. Ideally there would be ```pip``` package.

**Comment by anthrotype** [comment]
Well, there are "pip packages": that is, wheels, available from the GitHub releases page of this repository.
I guess you meant that these wheels should be also available from PyPI, so one can just do pip install brotli. Of course, I'm with you on that.

**Comment by pdknsk** [comment]
It didn't occur to me to try. That's good enough IMO, but should really be documented.
```Bash
pip install git+https://github.com/google/brotli/
```

**Comment by rleonhardt** [comment]
@anthrotype: could you change README.md and python/README.md accordingly to use
`pip install .` instead of `python setup.py install`?
And in addition for people who don't want to clone the repository first
`pip install git+https://github.com/google/brotli/`

**Comment by eustas** [comment]
Donw
