### ISSUE TITLE
a problem for brotli working on-the-fly

### ISSUE THREAD

**Issue by RenterRen** [google/brotli#356]
In my scene, I will not  finish compressing when I  run my program. so，BrotliCompressor object is only one. And on the client, I call the  BrotliStateInit(&s) just  for once.
So, like this:
while(1)
{
     I read 500 bytes to compress------->send to the client--->client decompress the data----> 
}
after client decompress  the data, the decompressed data is not 500, sometimes,it may be 200, sometimes,it may be 800, How can I resolve  the problem?

**Comment by RenterRen** [comment]
Waiting for your  response!

**Comment by RenterRen** [comment]
@khaledhosny please help!

**Comment by RenterRen** [comment]
@willnorris Can you help me?

**Comment by RenterRen** [comment]
@irori please help!

**Comment by RenterRen** [comment]
@eustas Can you help me?

**Comment by eustas** [comment]
When you compress block you need to set "force_flush" parameter to "true".
Moreover, after block is flushed, you need to append empty metadata block (WriteMetadata) to make sure that output is byte-aligned.

Sorry for confusing API. In two weeks API will be updated to make things like that more straightforward.

Best regards,
  Eugene.

**Comment by RenterRen** [comment]
@eustas  Do you mean that I need call the Api like this below: 
WriteMetaBlock(0, NULL, true, encoded_size, encoded_buffer);

if I set the parameter  of is_last  true,　means this is the last frame, but I hava no last frame In my system, If I call this, how about next data,data is not finished!

**Comment by eustas** [comment]
No, just something like this:
```
while (true) {
...
 c->CopyInputToRingBuffer(input_size, input);
...
 c->WriteBrotliData(/* is last */ false, /* force flush */ true, &output_size, output);
...
 c->WriteMetaBlock(/* input size */ 0, /* input */ nullptr, /* is last */ false, &output_size, output);
...
}
```

**Comment by RenterRen** [comment]
@eustas 
Hi eustas:
I  write the code like yours:

 while (true) {
      CopyOneBlockToRingBuffer(in, &compressor, &in_bytes, &final_block)
      out_bytes = 0;
    compressor.WriteBrotliData(false,true,&out_bytes, &output)
    printf("bbbbbbbbbbbbbbbbbbbb:%d\n",out_bytes);
    compressor.WriteMetaBlock( 0,NULL, false, &out_bytes, output);
    printf("ttttttttttttttttttt:%d\n",out_bytes);
  }

The test result is this:

bbbbbbbbbbbbbbbbbbbb:16126
ttttttttttttttttttt:0
bbbbbbbbbbbbbbbbbbbb:13349
ttttttttttttttttttt:0
bbbbbbbbbbbbbbbbbbbb:12419
ttttttttttttttttttt:0

How to fix it????
Best Regars:

**Comment by RenterRen** [comment]
@eustas 
please help!!!

**Comment by eustas** [comment]
Sorry for misguiding you. Use WriteMetadata instead of WriteMetaBlock.
And pay attention that unlike WriteBrotliData output buffer is provided by client, not by encoder.

**Comment by RenterRen** [comment]
@eustas 

Thanks your support, It seems to work!!!

**Comment by eustas** [comment]
You are welcome.
Soon we will publish v0.4 with more clear interface...
