### ISSUE TITLE
BrotliDecompressedSize fails for certain output sizes

### ISSUE THREAD

**Issue by jeroenooms** [google/brotli#365]
A user of the brotli R library has [reported](https://github.com/jeroenooms/brotli/issues/1) strange behavior of `BrotliDecompressedSize` failing for certain combinations of data and compression size.

I put a few example files [here](https://gist.github.com/jeroenooms/9fe37c9f04ad7f054dc2901a0bc5edaa). I compressed the file `uncompressed` with quality 3, 4, and 5 and default settings otherwise `mode = "generic"`, `log_win = 22`, `log_block = 0`.

```sh
git clone https://gist.github.com/jeroenooms/9fe37c9f04ad7f054dc2901a0bc5edaa
```

If I try to decompress the file `compressed3` via the C interface, the call to `BrotliDecompressedSize` fails. It does not happen for `compressed4` and `compressed5`. Also it does not seem to happen for the `bro` command line utility.

**Comment by eustas** [comment]
There is a very limited number of cases in which BrotliDecompressedSize works.
1) The whole input is compressed in a single block
2) The whole input is a single uncompressed block

The length of both compressed and uncompressed block is limited to 1 << 24 == 16MiB.

Technically it is possible to make this function work for a case: multiple uncompressed blocks followed by 0 or 1 compressed block.

**Comment by eustas** [comment]
Different compression levels affect ability of encoder to detect better input splitting...

**Comment by jeroenooms** [comment]
So how is the client supposed to know how much memory to allocate for `BrotliDecompressBuffer` if we cannot rely on `BrotliDecompressedSize` ?

**Comment by eustas** [comment]
Brotli is a low level format. It is designed for streaming processing.
We are planning to add framing format that will allow things like stream navigation, reliable calculation of uncompressed size, consistency checks, etc.
Unfortunately, it is not ready yet...

**Comment by jeroenooms** [comment]
OK so perhaps this is mostly a (lack of) documentation bug. I was under the impression that the most simple way to decompress was to allocate memory based on `BrotliDecompressedSize ` and run `BrotliDecompressBuffer`.

**Comment by eustas** [comment]
Hello.

Just recently updated `BrotliDecompressedSize`. Now it supports multiple non-compressed and metadata blocks. Unfortunately, until brotli framing format is implemented, it will never cover all the cases. So, currently, I would recommend to use `BrotliDecompressStream`.

As for encoder, `BrotliEncoderMaxCompressedSize` provides the exact answer about how large output may be; but it only works for `BrotliEncoderCompress`.

Thank you for the report and for the R bindings.
Best regards,
  Eugene.

**Comment by jeroenooms** [comment]
Have you pushed the updates for `BrotliDecompressedSize` yet?

**Comment by eustas** [comment]
Yup, in PR #386
