### ISSUE TITLE
BR content-encoding only works with static files like .css .js

### ISSUE THREAD

**Issue by RoldanLT** [google/brotli#393]
But not working on full html pages.

My config:
>brotli on;
>brotli_static on;
>brotli_min_length 1000;
>brotli_buffers 32 8k;
>brotli_comp_level 5;
>brotli_types text/plain text/css text/xml application/javascript application/x-javascript application/xml application/xml+rss application/ecmascript application/json image/svg+xml;

**Comment by eustas** [comment]
Hello. Perhaps you meant to post this issue to https://github.com/google/ngx_brotli/issues?
