### ISSUE TITLE
Don't assume __STDC_VERSION__ is defined

### ISSUE THREAD

**Issue by nemequ** [google/brotli#398]
See https://travis-ci.org/quixdb/squash/jobs/148061907#L1491

Note that this is coming from types.h, so it happens when compiling code *using* brotli, not necessarily in brotli itself.  Even if you don't care about `-Wundef` in brotli, IMHO it should be possible for people who just want to use brotli to use whatever warning flags they want.

Untested, but this should do the trick:

```diff
diff --git a/common/types.h b/common/types.h
index 4b050af..3508d74 100644
--- a/common/types.h
+++ b/common/types.h
@@ -25,7 +25,7 @@ typedef __int64 int64_t;
 #endif  /* defined(_MSC_VER) && (_MSC_VER < 1600) */
 
 #if (!defined(_MSC_VER) || (_MSC_VER >= 1800)) && \
-    (defined(__cplusplus) || __STDC_VERSION__ >= 199901L)
+    (defined(__cplusplus) || (defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L))
 #include <stdbool.h>
 #define BROTLI_BOOL bool
 #define BROTLI_TRUE true
```

**Comment by nemequ** [comment]
Closing since #399 fixes this; discussion (if necessary) can take place there.

**Comment by eustas** [comment]
Ungauarded __STDC_VERSION__ will be fixed in next encoder/decoder update.
