### ISSUE TITLE
Separate the public headers

### ISSUE THREAD

**Issue by khaledhosny** [google/brotli#4]
IMO, it would be cleaner to move the public headers to a separate `include` directory, and/or give them less generic names like `brotli-decode.h` and `brotli-encode.h`, to streamline the use of the library.

**Comment by lvandeve** [comment]
Hi,

Thank you for the comment. For now, if it helps, the headers that can be considered to contain the public API are "decode.h" and its included "streams.h" for the decoder, and "encode.h" and its included "streams.h" for the encoder.

**Comment by eustas** [comment]
Done. enc/encode.h and dec'decode.h now depend only on common/types.h
