### ISSUE TITLE
Appveyor skips uploading artifacts for 0.5.0 (complains tag already exists)

### ISSUE THREAD

**Issue by anthrotype** [google/brotli#408]
```
Deploying using GitHub provider
Creating "v0.5.0" release for repository "google/brotli" tag "v0.5.0" commit "2e0d3214c2b6248a486822d2c5267d1c961a29d0"...Skipped - release with tag "v0.5.0" already exists
No artifacts were published. Make sure you have specified correct artifacts filter.
```

https://ci.appveyor.com/project/szabadka/brotli/build/1.0.502/job/sstt93cb5onyte0w#L390

**Comment by anthrotype** [comment]
sorry, I jumped the gun. It is working fine.

**Comment by eustas** [comment]
Released as 0.5.1 to be safe

**Comment by anthrotype** [comment]
ops, I'm sorry I had you create the 0.5.1 tag... :(

**Comment by eustas** [comment]
No worries.

**Comment by anthrotype** [comment]
something might have gone wrong with the 0.5.0 tag. Some of the Windown 32-bit wheels are missing, as if subsequent builds on Appveyor have overwritten the existing Github release, deleting the files uploaded by the previous build.
So let's cross fingers with 0.5.1...

**Comment by anthrotype** [comment]
ouch. The upload to 0.5.1 is now working fine from Appveyor, but the version string in the setup.py is still 0.5.0, so the wheels are named like that...

The solution is deprecate 0.5.1, commit a version string change (0.5.2?), and cut a new tag.
Sorry you have to go through this mess.

**Comment by anthrotype** [comment]
the `BROTLI_VERSION` in `tools/version.h` should match the latest tag version.

There are tools lik `setuptools_scm`, which take care of updating the package version (as well as the one in the header file) based on the latest git tag, when one generates a new source distribution, so that you won't need to remember to manually update the version file, but simply make an annotated tag.

But maybe that's overkill.

**Comment by anthrotype** [comment]
for the python packages to have the right version string (matching the latest tag) you need to modify the `tools/version.h` file like this:
 
https://github.com/google/brotli/blob/master/tools/version.h#L12

```diff
-#define BROTLI_VERSION "0.5.0"
+#define BROTLI_VERSION "0.5.2"
```

**Comment by eustas** [comment]
Ooops. Released from master instead of branch.

**Comment by anthrotype** [comment]
still no luck. :(
the 3.4 and 3.5 mac wheels in 0.5.2 release are still using 0.5.0 version
https://github.com/google/brotli/releases/tag/v0.5.2

**Comment by anthrotype** [comment]
actually no! they are just duplicate. The ones with the correct 0.5.2 version are also there.
Can you please manually delete the 0.5.0 ones, to avoid any confusions?
Thank you very much.

**Comment by eustas** [comment]
Done =)

**Comment by anthrotype** [comment]
Thanks! Looks good now 👍
