### ISSUE TITLE
Command line explanation missing

### ISSUE THREAD

**Issue by rugk** [google/brotli#409]
``` console
$ ./bro -h                                       
Usage: ./bro [--force] [--quality n] [--decompress] [--input filename] [--output filename] [--repeat iters] [--verbose] [--window n] [--custom-dictionary filename]
```

This output is very few. E.g. I don't know what the `--repeat` or `--window` switches do.

**Comment by eustas** [comment]
Going to revamp command line tool soon.
Planned changes:
 * more gzip-like arguments
 * better help message
 * man page
 * rename to 'brotli' to avoid clash with existing `/usr/bin/bro` tool

**Comment by marchante0** [comment]
Any progress in this regard yet?

**Comment by eustas** [comment]
Already done =)

**Comment by concatime** [comment]
Awesome! Just continue like this!
