### ISSUE TITLE
Do not change file modification date & permissions

### ISSUE THREAD

**Issue by rugk** [google/brotli#410]
gzip sets the file modification time of the new `.gz` file to match the original file. Brotli does not do that. Do you consider adding this feature?

GZIP does also inherit the permissions of the original file - in contrast to Brotli.

Tasks:
 - [x] preserve original file modification date
 - [x] preserve original file permissions

**Comment by eustas** [comment]
Going to add this behavior soon.

**Comment by eustas** [comment]
Should be "fixed" with PR #431 
Thought it is barely minimal implementation,... please check if helps in your case.
