### ISSUE TITLE
Wheels / Windows

### ISSUE THREAD

**Issue by JoeArizona** [google/brotli#412]
Hi guys, what are the wheels files supposed to do? I installed a wheel thinking it would build a binary, but it didn't.

Relatedly, what's the simplest way to build brotli on Windows? I see make, cmake, premake, the notes mention Bazel. I'm not familiar with the last two. What's the best Windows path here? (64-bit, Windows 10, VS 2015)

**Comment by eustas** [comment]
With VS it is logical to use build system that supports project file generation -> cmake or premake5:
* for cmake run `cmake -G "some_generator"`, where _some_generator_ is picked from the list provided by `cmake --help`
* for premake5 run `premake5 vs2015`

Of course, installed cmake/premake5 is a prerequisite.

**Comment by anthrotype** [comment]
@JoeArizona [Wheels](https://www.python.org/dev/peps/pep-0427/) are Python's binary package format.

**Comment by JoeArizona** [comment]
Hey thanks @eustas, I'm reading about premake now, and it looks pretty smart. premake5 is in alpha though, and 4.4 is in beta, so I'm puzzled by what version they want people to use, since those are the only downloads they feature. I'll try CMake. Exposing compiler optimizations in these tools has always been harder than it needs to be, buried in so much other content that it feels like compiler flags are an afterthought. Build tools should have a section in their make-equivalent files called **Optimization**, with subsections for CPU/hardware targets, linker optimization, math, etc. and then automatically convert all that to the correct compiler flags depending on the compiler. Maybe I'll sketch out something.

@anthrotype I know that much, have occasionally gone to Christoph Gohlke's wonderful [repository of Python wheels for Windows](http://www.lfd.uci.edu/~gohlke/pythonlibs/) to grab stuff, but I don't know what the _brotli_ wheel is supposed to do exactly, since brotli isn't written in Python. I guess another way of framing my question: What do we need the Python stuff for here? What is Python doing in the brotli repo? I'm not used to seeing a bunch of Python/Ruby/scripting code in a compression codec written in C/C++. If we don't need it to build the binaries, then is for testing or something? I looked around for an explanation of the build process, and also of what the Python code was for, but so far I haven't found any docs or comments on that.

**Comment by anthrotype** [comment]
@JoeArizon They are simply bindings which allow to call the brotli library from python code (Python has C API which can be used to write extension modules).
For example, we use brotli for compressing WOFF2 fonts in [FontTools](https://github.com/behdad/fonttools).

**Comment by JoeArizona** [comment]
Ah, okay, just bindings. The nine different wheels in the downloads/releases page threw me off, made me think wheels were being used to build brotli.exe. Thanks for clearing that up.

**Comment by anthrotype** [comment]
Yeah, those should really be uploaded to the Python package index, IMO.
