### ISSUE TITLE
create 7-Zip plugin

### ISSUE THREAD

**Issue by StephanBusch** [google/brotli#413]
please create a plugin for 7-Zip so that this open and free archiver can also compress images using FLIF.
This would also help making Brotli more famous in the world.

there are already plugins that work with 7-Zip (including descriptions and sources):

ZSTD

https://github.com/mcmilk/7-Zip-Zstd

LZHAM
http://richg42.blogspot.de/search?updated-max=2015-12-03T16:22:00-08:00&max-results=7&start=21&by-date=false
https://github.com/richgel999/lzham_codec_devel

**Comment by eustas** [comment]
Creating plugin is a nice initiative, but... then it will be a painful experience for users: they expect that everything works out of the box. Perhaps, it will be more efficient to negotiate with Igor Pavlov (7-Zip author), to make Brotli the part of official distribution.

**Comment by eustas** [comment]
Meanwhile, to play with different compressors one can use [Squash](https://quixdb.github.io/squash/) - Compression Abstraction Library. It already has 31 compressor plugin (including Brotli) and has bindings for Vala and Rust.

**Comment by mcmilk** [comment]
I am creating an 7-Zip plugin for brotli. Currently there seems to be no special magic for testing of brotli's presence in some data.

I found some first definitions of a frame format v3 in the brotli repository of @madler ... but that's it.

For my 7-Zip extension, the stream with the container will be defined like this:
- 12 bytes skippable frame
  - 4 bytes magic id 0x184D2A50U
  - 4 bytes length of the skippable frame (always 4)
  - 4 bytes with the length of the following compressed data, CLEN (including 4 bytes magic)
- 4 bytes magic id in the beginning of compressed data: "BROT"
- CLEN bytes compressed data stream to be decoded

But I could also support "normal" brotli streams, if I can recognize them.

AFAIK, Igor will not add new codecs to Standard 7-Zip currently.

**Comment by mcmilk** [comment]
I think this issue can be closed now, cause you have an [7-Zip plugin for brotli](https://github.com/mcmilk/7-Zip-Zstd) now ;-)

**Comment by eustas** [comment]
Cool! 👍
