### ISSUE TITLE
Combine port.h files

### ISSUE THREAD

**Issue by mdejong** [google/brotli#425]
Hello

I recently compiled brotli under Xcode for use in an iOS project and I hit one little snag. The files dec/port.h and common/port.h have the exact same filename and this makes it difficult to setup an Xcode project where all the brotli files live in one directory. Could you please rename common/port.h to common/common_port.h (or perhaps common/cport.h) so that it is possible to import these files into an Xcode project without a conflict. The built in include files logic in an Xcode project are a little weird and this change would make things a lot easier.

**Comment by eustas** [comment]
Does this problem occurs with CMake or Premake5 generated XCode projects?

**Comment by mdejong** [comment]
No, I am building in Xcode but creating a new directory layout and the only catch is the fact that the same filename is being used in different directories. It is not a problem if you don't change anything and use the existing build structure, but then it is harder to integrate into an existing Xcode project as source code.

**Comment by eustas** [comment]
Ideally, there will be only one port.h, and we are moving towards this.
Feel free to ping me, if this is urgent.

**Comment by eustas** [comment]
Will be fixed in #630
