### ISSUE TITLE
Java implementation of Brotli

### ISSUE THREAD

**Issue by hulaud** [google/brotli#428]
Right now the only way to use Brolti in the backend is to use the Java binding for Brotli (JNI). It is not always possible to run native code in backend. Could Google release a pure Java implementation of Brotli to facilitate its adoption. I am mostly interested in the decompression part.

**Comment by eustas** [comment]
Hello. We already have pure Java decoder.
Unfortunately its quality isn't proven, so it is too early to release it.
I hope this will arrive shortly after v1.0.0 brotli release that is getting closer and closer.

**Comment by eustas** [comment]
Good news: we have decided to publish this draft very soon (before v1.0.0).

**Comment by eustas** [comment]
Update: we have more-or-less working java decoder now =) going to publish it early next week.

**Comment by hulaud** [comment]
@eustas great news!!! Thanks :)

**Comment by eustas** [comment]
Done. Going to push to Maven Central, but it might take a considerable amount time.

**Comment by eustas** [comment]
poms are wrong (but still work). Going to fix them ASAP.

**Comment by jstlnd** [comment]
Any ETA on when this can be published to Maven Central?

**Comment by eustas** [comment]
Next week, I hope.

**Comment by jstlnd** [comment]
Awesome! Thanks!

**Comment by bgleib** [comment]
Hello! Any updates on this being published? Thanks!

**Comment by eustas** [comment]
Sorry for the delay (again). Now, I think it will be on the next week. Sorry.

**Comment by crm416** [comment]
Sorry to ask again, but any updates on the publish?

**Comment by eustas** [comment]
Still waiting for brotli.org to be made online. Sorry.

**Comment by eustas** [comment]
org.brotli.dec is now accessible on Maven Central =)
https://search.maven.org/#search%7Cga%7C1%7Corg.brotli.dec

**Comment by jstlnd** [comment]
Cool! Thanks for letting us know.

**Comment by CAFxX** [comment]
Are there any plans to also implement the encoder?

**Comment by mkarg** [comment]
Looking at the mass of Java based services it would be really cool to have a Java-implemented encoder. Are there any plans for that, and if not, what are the reasons? Or are you just waiting for volunteers?
