### ISSUE TITLE
Nasty bug in modp_dtoa

### ISSUE THREAD

**Issue by jeroenooms** [google/brotli#430]
I got bitten by a this long standing bug in `modp_dtoa{,2,3}`: https://github.com/client9/stringencoders/issues/40. I was able to reproduce it with brotli as well.

The following values should rond to `1.0` but instead return `0.1`

```c
modp_dtoa(0.95, str, 1); 
modp_dtoa(0.9999995, str, 6); 
```

Unfortunately upstream does not seem to be maintained anymore.

**Comment by eustas** [comment]
Could you point where it is used in brotli, please.
The only double-to-string conversion occurs in "bro" tool...

**Comment by jeroenooms** [comment]
Apologies, I seem to have mixed up with another repository.
