### ISSUE TITLE
Travis silently fails when builds cmake/gcc4.4 combination

### ISSUE THREAD

**Issue by eustas** [google/brotli#453]
https://travis-ci.org/google/brotli/jobs/168940272

**Comment by eustas** [comment]
May it be ralated to https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/ ?

**Comment by eustas** [comment]
Homebrew gcc44 formulae is not supported for OS versions newer than maverics

**Comment by anthrotype** [comment]
You could tell Travis CI to use Mavericks by specifying `osx_image: beta-xcode6.1` or `osx_image: beta-xcode6.2`.
See https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by eustas** [comment]
Thanks, fixed this way.
