### ISSUE TITLE
Java port for encoder coming up?

### ISSUE THREAD

**Issue by kjatin** [google/brotli#466]
I see the decoder has been ported to Java recently. Are there plans for porting encoder to Java as well?

**Comment by eustas** [comment]
Currently we have no plans for Java encoder port. But, for sure, we will have JNI bindings.
Encoder is complex and we try to use all the power of CPU to be competitive.
With Java it is much harder to match plain C performance.

However, it is possible that some subset of encoder (levels 0, 1, or something similar) will be ported to support specific use cases.

**Comment by dominikhlbg** [comment]
I did release a java encoder of brotli. https://github.com/dominikhlbg/BrotliHaxe

**Comment by eustas** [comment]
Merging into #405
