### ISSUE TITLE
Split pc file into encoding and decoding libraries

### ISSUE THREAD

**Issue by fred-wang** [google/brotli#473]
A woff2 generator or consumer will generally use only one of this library so it's better to have separate pc files. This is how it was done in @bagder 's initial commit but @nemequ only created a single pc file.

There were discussions about the names to use for pc files, but I'm not sure how important it is.

**Comment by fred-wang** [comment]
@eustas Are you going to take care of this?

**Comment by eustas** [comment]
Surely. Will try to do it today.

**Comment by eustas** [comment]
Please take a look at #490

**Comment by fred-wang** [comment]
Thanks. I trust you @eustas !
