### ISSUE TITLE
Release the Python GIL when compressing/decompressing

### ISSUE THREAD

**Issue by thedrow** [google/brotli#476]
The C extension doesn't currently release the GIL during [`compress_stream()`](https://github.com/google/brotli/blob/master/python/_brotli.cc#L92) and during `decompress_stream()` (between https://github.com/google/brotli/blob/master/python/_brotli.cc#L433 and https://github.com/google/brotli/blob/master/python/_brotli.cc#L452 which is a shame because we can enable greater parallelism .

**Comment by eustas** [comment]
Will `Py_BEGIN_ALLOW_THREADS` / `Py_END_ALLOW_THREADS` do the trick, or we need something more exotic?

**Comment by thedrow** [comment]
Nope, that should do the trick.
