### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by thedrow** [google/brotli#483]
There has been some API changes since 0.5.x.
It'd be great to have a new release tagged so that we can use them.

**Comment by eustas** [comment]
There were tiny changes.
I'd be glad to tag with 1.0.0, but to do that, we need to remove functions tagged "DEPRECATED" first.
I'm going to ask ngx_brotli if they can stick to some specific commit, so this removal won't hurt them.

**Comment by thedrow** [comment]
Any news on this? We're waiting for the 1.0 release in order to upgrade the Ruby implementation.

**Comment by eustas** [comment]
I've prepared a patch for ngx_brotli, but it may take some time to land it (because of the holidays).

**Comment by fred-wang** [comment]
@eustas ¿Any update on this?

**Comment by eustas** [comment]
We're getting closer =) Just yesterday brotli.org became live...
The only thing that holds now is nginx-brotli module. It uses deprecated API, I plan to remove before releasing 1.0.0

**Comment by jimjag** [comment]
Why hold off others who could use it, like Apache httpd, because of work needed for nginx?

The world is waiting! Please don't show preferential treatment! :) :)

**Comment by eustas** [comment]
Just discovered that ngx_brotli now depends on brotli via git submodule -> we are unblocked to move further =)
So, the plan is: release 0.6 with as brotli is now, and soon after that 1.0.0 with deprecated API removed.

**Comment by jimjag** [comment]
Any update on the status of a release?

**Comment by eustas** [comment]
Just recently sent a PR with latest updates.
After it is landed, we can start releasing 0.6.0 =)

**Comment by fred-wang** [comment]
Is it https://github.com/google/brotli/pull/520 ? It seems to be green ;-)

**Comment by jimjag** [comment]
Anything I/we can do to help?

**Comment by jimjag** [comment]
Any update on this? We (the Apache httpd PMC) were looking to doing a 2.4.26 release soon, and it would be great to be able to include mod_brotli; but we can't depend on an unreleased lib and the module requires the "new" API.

Thanks!

**Comment by eustas** [comment]
v0.6.0 is released. Sorry for the delays.

**Comment by eustas** [comment]
v1.0.0 is coming soon.

**Comment by jimjag** [comment]
WOOT!! Super Thx!

**Comment by fred-wang** [comment]
@eustas Great, thanks! Do you also plan to submit a PR to google/woff2 to upgrade brotli when v1.0.0 is released?

**Comment by eustas** [comment]
Surely.

**Comment by fred-wang** [comment]
> v1.0.0 is coming soon.

@eustas Do you have any idea about when v1.0.0 will be released?

**Comment by eustas** [comment]
Technically, with `bro` being replaced with `brotli`, and recent tiny API additions, we are ready to do it =)

Going to see through issues list and, hopefully, new release will happen next week.

**Comment by fred-wang** [comment]
> Going to see through issues list and, hopefully, new release will happen next week.

@eustas Sorry for pushing again, but are there still things blocking the 1.0.0 release?

**Comment by eustas** [comment]
I'm terribly sorry, but... the answer is again - very soon.
We have found that "Custom Dictionary" feature is somewhat confusing and misleading...
So we are going to "unland" it this week. After that our API is clean and concise and 1.0 ready.
Hopefully, it is the last delay. No more "sooner" - we will just release it =)

**Comment by fred-wang** [comment]
@eustas So it was https://github.com/google/brotli/pull/581 ?

**Comment by eustas** [comment]
Yup. Now going through open issues. Perhaps one more will be addressed before release - building both static and dynamic libraries by CMake. It looks painful, as it will double compilation time, but, I suppose, a necessary thing...

**Comment by fred-wang** [comment]
@eustas So I guess there is still delay...  :-(

Just FYI, the web engines hackfest 2017 edition is in one month and I hope we would have a release of brotli with stable API since then so that we can package it in distros and start the work for WOFF2 too... with the goal of having at least Linux browsers using system libraries for web fonts.

**Comment by eustas** [comment]
Releasing brotli tomorrow!
Just set one day to settle the dust of the latest changes.

**Comment by eustas** [comment]
:tada: Woohoo! Brotli **v1.0.0** is released now :tada:

**Comment by thedrow** [comment]
Yay!

**Comment by fred-wang** [comment]
@eustas Great, thanks and congrats!!!! Do you plan to you plan to submit a PR to https://github.com/google/woff2 to upgrade it to brotli 1.0.1???

**Comment by eustas** [comment]
Of course. This will be my first priority next week.

**Comment by naufdotal** [comment]
any update for ngx_brotli ?
