### ISSUE TITLE
Potential buffer over-reads due to incorrect masking

### ISSUE THREAD

**Issue by randomascii** [google/brotli#493]
When building Chromium with the v1.0.0 version of Brotli using the VC++ /analyze feature I see the following warnings:

brotli\enc\compress_fragment_two_pass.c(461) : warning C6385: Reading invalid data from 'cmd_histo':  the readable size is '512' bytes, but '1024' bytes may be read.
brotli\enc\compress_fragment_two_pass.c(474) : warning C6385: Reading invalid data from 'cmd_bits':  the readable size is '256' bytes, but '512' bytes may be read.
brotli\enc\compress_fragment_two_pass.c(474) : warning C6385: Reading invalid data from 'cmd_depths':  the readable size is '128' bytes, but '256' bytes may be read.
brotli\enc\compress_fragment_two_pass.c(475) : warning C6385: Reading invalid data from 'kNumExtraBits':  the readable size is '512' bytes, but '1024' bytes may be read.
brotli\enc\static_dict.c(90) : warning C6385: Reading invalid data from 'kBrotliDictionarySizeBitsByLength':  the readable size is '25' bytes, but '128' bytes may be read.

Manual examination of these warnings suggest that they are all valid. In all cases an index is being anded with a bit mask but the bit mask has too many set bits.

In the first four cases a bit mask of 0xff is used by the arrays only have 128 elements. It would be safer to define a COUNTOF macro and change the code like this:

    ++cmd_histo[commands[i] & 0xff];

to something like this:

    ++cmd_histo[commands[i] & (COUNTOF(cmd_histo) - 1)];

Or, just change the constant to 0x7f, or use a named constant to make sure they stay in sync.

The fifth warning is a bit different because the index is being masked down to 0-127 but the array is 25 elements long. This seems odd. If the value of 'len' is guaranteed to be in range then the masking is not needed, and if isn't guaranteed to be in range then the masking is insufficient. Maybe there is other data in the high bits of 'len' - I can't tell. The safest thing to do, it seems, would be to pad kBrotliDictionarySizeBitsByLength out to 32 bytes (at a cost of six bytes of storage) and then mask with 0x1f instead of 0x7f.

**Comment by eustas** [comment]
About static_dict: it is masked with 0x7F to filter out highest bit. Going to add assert + comment + expand  kBrotliDictionarySizeBitsByLength and make mask more narrow; just to be on a safe side.

**Comment by eustas** [comment]
As for other cases: this never can happen, according to BL (take a look at `EmitXXX` functions).
We mask with 0xFF for performance reasons (it turns to `movzbl` instead of real masking).
Going to add asserts to calm down VC++

**Comment by randomascii** [comment]
Thanks for the explanation.  VC++ gives many warnings in its /analyze mode and I ignore many of them, so I am fine with ignoring these as well. However they pointed out constructs which were suspicious - which looked wrong to a human eye. Comments to explain that the mask amounts are in fact correct (and why) would be sufficient I think. Suppressing /analyze warnings is a black art and making the code clear for human readers is more important, IMHO.

**Comment by eustas** [comment]
Should be fixed with #497
