### ISSUE TITLE
threadsafety?

### ISSUE THREAD

**Issue by marcuskbr** [google/brotli#501]
Recently I get SEGV signals inside the brotli directory decoding content of Youtube and I was wondering if this brotli library is threadsafe ?
I.e. can I use multiple threads that repeatedly do this:
```
bstate = BrotliDecoderCreateInstance( NULL, NULL, NULL );
bretval = BrotliDecoderDecompress( ... );
BrotliDecoderDestroyInstance( bstate );
```

**Comment by eustas** [comment]
Brotli does not use any shared mutable data; but there are no explicit memory barriers.

So, as long as all things with a single instance are done within one thread - it is safe; every thread may work with as many instances as it wants.

But as soon as instance is passed between threads, developer should take care of exclusive access to the instance and appropriate memory barriers.

**Comment by eustas** [comment]
I believe this model is called "[conditionally safe](https://en.wikipedia.org/wiki/Thread_safety)".
