### ISSUE TITLE
Java decoder is slow

### ISSUE THREAD

**Issue by mzule** [google/brotli#508]
BrotliInputStream with brotli format is much slower than GZIPInputStream with gzip format. Is there any performance problem with java decoder?

Some statistics generated on my android device (xiaomi 4):

data size | format | decode cost (ms)
---|---|---
1kb | br | 4.46
1kb | gzip | 1.38
12kb | br | 17.36
12kb | gzip | 4.35
46kb | br | 52.59
46kb | gzip | 8.66
112kb | br | 82.91
112kb | gzip | 15.63
365kb | br | 247.37
365kb | gzip | 41.47

**Comment by eustas** [comment]
GZIPInputStream is based on native library. 
BrotliInputStream is a pure java implementation for platforms/products where embedding of native code is not allowed. For other platforms JNI wrapper should be used.

**Comment by mzule** [comment]
Yes! JNI wrapper is much more efficient. Time cost is even less than gzip. Thank you!

data size | format | decode cost (ms)
---|---|---
1kb | br | 0.47
12kb | br | 1.44
46kb | br | 3.88
112kb | br | 6.53
365kb | br | 17.98
