### ISSUE TITLE
0.6.0 Package README.md bears no relationship to build schemas of 0.6.0 package.

### ISSUE THREAD

**Issue by wrowe** [google/brotli#539]
Quoting; 
$ more README.md
To build and run tests, simply do:

    $ ./configure && make

If you want to install brotli, use one of the more advanced build systems below.

#### Bazel

See [Bazel](http://www.bazel.build/)

#### CMake

The basic commands to build, test and install brotli are:

    $ mkdir out && cd out && ../configure-cmake && make
    $ make test
    $ make install

You can use other [CMake](https://cmake.org/) configuration. For example, to
build static libraries and use a custom installation directory:
^C

$ ls
common           dec  include  MANIFEST.in  python     setup.cfg  tools
CONTRIBUTING.md  enc  LICENSE  PKG-INFO     README.md  setup.py

**Comment by wrowe** [comment]
Find it especially strange that the Brotli-0.6.0.tar.gz contents seem have significant discrepancies with https://github.com/google/brotli/tree/v0.6

**Comment by eustas** [comment]
It seems to be a wrong name for the file. Actually, sources are for python-module distribution.
We are on the way of splitting it out to brotli-wheels subproject...

Going to make an add full source release artifact, and extend README ASAP.

**Comment by eustas** [comment]
"Source Code" is the right link. It contains the full copy of repo.
It is overweighted (19MiB),  because it contains pdf, images and other garbage.
In next release going to create a distilled version, with no garbage, just sources, meta, and tests.

**Comment by anthrotype** [comment]
Yes, as @eustas said, that is the source distribution for the python module. It's generated by the `python setup.py sdist` command using patterns from the `MANIFEST.in` file.
Sorry I couldn't find the time to work on the brotli-wheels yet as I promised. I will get to it soon..
The idea is that Travis/Appveyor CI for this repo should no longer do the python packaging and deployment tasks, but only build and run the tests. The other separate repository will use this one as submodule, and upload artifacts to PyPI for distribution.

**Comment by wrowe** [comment]
Thank you anthrotype - yes it is not clear in this list the purpose of Brotli-0.6.0.tar.gz;

**Comment by anthrotype** [comment]
there is no distinction between Brotli-0.6.0.tar.gz and Brotli-0.6.0.zip; they are both sdist packages, which are meant to be uploaded to the Python Package Index and used by the `pip` installer, e.g. when one does `pip install brotli`, and when the there are no binary "wheel" packages available for the python version/platform/architecture the user is running.
We shall get rid of those before the next tag, for now you can just ignore them.
