### ISSUE TITLE
--disable-shared-libs has no effect

### ISSUE THREAD

**Issue by JoeUser78** [google/brotli#542]
Compiling 0.6.0 with cmake and --disable-sharesd-libs as documented in the README has absolutly no effect.
What is the correct way to build static libs and binary for 0.6.0 with cmake?

**Comment by JoeUser78** [comment]
Corresponding FreeBSD bugreport:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=218851

**Comment by eustas** [comment]
Going to investigate ASAP (== tomorrow)

**Comment by eustas** [comment]
Current workaround for simple build cases would be:
 * `cmake . && make` for static libraries
 * `cmake . -DBUILD_SHARED_LIBS=ON && make` for shared libraries

Digging further, why this machinery doesn't work as expected.

**Comment by JoeUser78** [comment]
OK, -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON did it, thanks.

**Comment by eustas** [comment]
Thanks for the report. Going to update readme, and, most probably, release 0.6.1 after fixing buildfiles.

Line `CMAKE_DEPENDENT_OPTION(BUILD_SHARED_LIBS "Build shared libraries" ON "NOT BROTLI_BUNDLED_MODE" OFF)` is read as "if not in bundled mode (== top level project) then, by default, set BUILD_SHARED_LIBS=ON". For some reason, this magic didn't happen. That is what configure-cmake flag has no effect.

**Comment by JoeUser78** [comment]
Thanks for your realy fast response and fix.

**Comment by eustas** [comment]
Oh, I have a guess what has happened! CMake is a very nasty build system. If you occasionally use it in root project folder - you poison it. CMake will cache some variables and do unexpected things based on cached values.

That is why there is `mkdir out && cd out` and `mkdir out-static && cd static-out` in readme.

To cure the poisoned repository try `git reset --hard && git clean -dfx`.

**Comment by JoeUser78** [comment]
My builds had always been out-of-source builds (FreeBSDs Ports Makefile option `USES=cmake:outsource`), so that this is not the course of the issue. Also i'm not using git but the released source code archive (`v0.6.0.tar.gz`).

**Comment by osokin** [comment]
Hi,

actually we'd like to see both types of libraries (shared and static) like other ports do.

Is there any chance to see three types of a build, i.e. SHARED, STATIC, COMBINED (SHARED_AND_STATIC).

Thanks in advance.

**Comment by eustas** [comment]
Going to see, if it is possible. If you point to a sample project with CMake build, that features such option, it will help greatly.

**Comment by JoeUser78** [comment]
https://cmake.org/Wiki/CMake_FAQ#Library_questions should help a bit.

**Comment by eustas** [comment]
Updated cmake to build both shared and static libraries the same time
