### ISSUE TITLE
[feature request] Optimize input encoding schemes (base64, etc.)

### ISSUE THREAD

**Issue by buu700** [google/brotli#549]
I'm not extremely familiar with the internals of Brotli or compression in general, so this may be a naive suggestion, but intuitively I think it aligns philosophically with Brotli's use of a built-in dictionary. Would it be practical for Brotli to detect strings of formats like base64 and hex and decode them to binary before compressing / re-encode them as part of the decompression process?

I noticed just now during a comparison between compressing a binary file and the equivalent base64 (https://github.com/kripken/emscripten/issues/5104#issuecomment-302939570) that the base64 version ended up a bit larger, which it occurs to me shouldn't need to be the case given that the two contain almost exactly the same information.

**Comment by eustas** [comment]
Thanks for the suggestion, but we tend to keep brotli compressor pure.
This is a feature for brotli framing format: #462.
Could you place your FR into framing format discussion, please.

**Comment by buu700** [comment]
Got it, thanks, I'll post it there.
