### ISSUE TITLE
I've added Brotli to the Fedora repos

### ISSUE THREAD

**Issue by pouar** [google/brotli#551]
https://admin.fedoraproject.org/pkgdb/package/rpms/brotli/
It's currently in testing btw
https://bodhi.fedoraproject.org/updates/?packages=brotli

**Comment by eustas** [comment]
Thanks! :+1:

**Comment by fred-wang** [comment]
cc @mcatanzaro

**Comment by mcatanzaro** [comment]
Awesome! Next step is to un-bundle it from WebKit....
