### ISSUE TITLE
Multithreaded brotli within 7-Zip

### ISSUE THREAD

**Issue by mcmilk** [google/brotli#553]
I have just released a new version of [7-Zip ZS](https://github.com/mcmilk/7-Zip-zstd).

Within the 7z-Zip container, the threading is done with [skippable frames](https://github.com/mcmilk/zstdmt) like in [ZStandard](https://github.com/facebook/zstd/).

All levels (0..11) use a default windows size of 24.

Here is a screenshot of it:
![Methods](https://mcmilk.de/projects/7-Zip-zstd/Methods.png "Methods with Brotli")

Compression / decompression of `.br` files can be added also, when I have some MAGIC's therefore.

I have done also some benchmarking:
![Compression Speed vs Ratio](https://mcmilk.de/projects/7-Zip-zstd/dl/compr-v120.png "Compression Speed vs Ratio")
![Decompression Speed](https://mcmilk.de/projects/7-Zip-zstd/dl/decomp-v120.png "Decompression Speed per Level")

Does the implementation look okay for you, or are there any issues with it ?

**Comment by eustas** [comment]
Thank you, Tino!
Added link to README.md.
