### ISSUE TITLE
Verbose flag does nothing?

### ISSUE THREAD

**Issue by jboero** [google/brotli#571]
In my quest to understand the format, I would expect -v, --verbose flags to show more output.  I started to write a verbose decoder from scratch but then noticed the excellent research/brotlidump.py script which is ultra helpful (once you copy dictionary.bin to ./).  It would be nice if this kind of output came from -v.  Will implement myself if necessary.

**Comment by eustas** [comment]
Hello. Thank you for your interest to `brotli` project.

In verbose mode CLI should provide some information useful to users: compression progress, ratio, speed, etc. Currently it is not implemented, just reserved, to make CLI more stable.

Format explanation is very different, and affects performance, even when off. `brotlidump` is the best choice for that. But it requires some care, as it might not work out of the box.

If you would like to invest your time/efforts in this direction, we would be grateful, if you work on `brotlidump` improvements.
