### ISSUE TITLE
Command "python setup.py install" not work :-(

### ISSUE THREAD

**Issue by AksarWeb** [google/brotli#576]
python setup.py install 
not work. error:
C:\DevTools\Python\python.exe: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by AksarWeb** [comment]
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> python setup.py install
  File "<stdin>", line 1
    python setup.py install
               ^
SyntaxError: invalid syntax

**Comment by jmoceri34** [comment]
I'm unable to reproduce this, and was able to do it successfully.

Make sure you're at the root project directory ([reference](https://github.com/google/brotli/blob/master/python/README.md)), running:

```bash
python setup.py install
```

**Comment by nicksay** [comment]
@AksarWeb I've updated the documents in #578 to hopefully make it a bit clearer
