### ISSUE TITLE
0.6.0 compression is slow (or never finishes?) for data over ~1.57MB

### ISSUE THREAD

**Issue by jotto** [google/brotli#584]
It might have to do with randomness in the file - I can easily compress a large file of zeros, but not JPGs over ~2MB or /dev/random over ~1572864 bytes.

```javascript
// brotli.js
const fs = require("fs");
const compressSync = require("iltorb").compressSync;

const args = process.argv.slice(2);
const filename = args[0];

console.time("compress");
const output = compressSync(fs.readFileSync(filename));
console.timeEnd("compress");
console.log(output.length, "bytes");
```

```bash
// increase to 1572865 to see it fail/stall (or you might need to go a little higher)
dd if=/dev/urandom bs=1 count=1572864 > brotli.txt
node brotli.js brotli.txt
```

**Comment by eustas** [comment]
Going to investigate it on Monday.

**Comment by eustas** [comment]
Haven't done investivation, just inspected the code.
This loop looks suspicious: https://github.com/MayhemYDG/iltorb/blob/master/src/enc/stream_encode_worker.cc#L25
See - no output space is given; if it happens, that internal brotli output buffer is full - it can't continue processing... so it becomes infinite loop...
Outer wrapper also doesn't care, if chunk is too big to make "StreamEncodeWorker" choke...
