### ISSUE TITLE
Release executable

### ISSUE THREAD

**Issue by svnpenn** [google/brotli#591]
This project is in C, but the releases are Python WHL? What gives

**Comment by anthrotype** [comment]
wheel packages will no longer be uploaded to Github for next releases, as they are automatically published on the Python Package Index.
https://github.com/google/brotli/pull/583

**Comment by eustas** [comment]
Releasing executable is a slippery road - there are tons of different OS / CPUs. Releasing for some of combinations would make people unhappy, that their favorite combination is not supported.
That is why binaries are released via appropriate binary distribution systems, e.g. HomeBrew or PyPI or linux distros.
If you have some specific OS / CPU in mind, we would be glad to try to support specific binary distribution system.

**Comment by svnpenn** [comment]
Well, Windows would be a start, seeing how Zstd, Lizard and LZ4 are already
doing that:

- http://github.com/facebook/zstd/releases
- http://github.com/inikep/lizard/releases
- http://github.com/lz4/lz4/releases

**Comment by Aris-t2** [comment]
Agreed, executables for Windows (32/64 bit) would be a great start.

**Comment by eustas** [comment]
After #596 windows binaries will be accessible as build artifacts.

**Comment by eustas** [comment]
Latest build could be taken from here: https://bintray.com/eustas/brotli/bin/snapshot/view/files?sort=name&order=asc#files/
Next release will contain those artifacts as well.

**Comment by eustas** [comment]
"Next release" happened on Sep 21, 2017. It actually contains windows artifacts: https://github.com/google/brotli/releases/tag/v1.0.0

Later (1.0.1 and 1.0.2) are minor sub-releases, mostly concenred about non-Windows build tools.

Going to attach windows artifacts to the next sub-release (1.0.3) when it is ready.

**Comment by Cladge** [comment]
Hi. The last release that included Windows binaries was v1.0.4. The 3 releases since then have only included the source code. Have you stopped providing Windows binaries?

**Comment by DanielRuf** [comment]
Since bintry was deprecated ans closed by jfrog, where can we get the new builds now?

I need prebuilt binaries for webservers / hosting setups and building them myself is not an option.

**Comment by eustas** [comment]
I'm working on migration to github actions right now. Whet it is finished, binaries from the latest build will be always available.

**Comment by garretwilson** [comment]
Did you stop releasing Windows binaries again? The latest release I can find with Windows binaries is [v1.0.4](https://github.com/google/brotli/releases/tag/v1.0.4), which is four years old.

Or are Windows binaries somewhere else now?

**Comment by mirh** [comment]
https://github.com/google/brotli/actions/workflows/release.yaml

**Comment by mirh** [comment]
I suppose all links in my previous reply are expired by now. 
Thankfully I still had the executable I downloaded back then saved 
https://github.com/google/brotli/files/11469899/brotli.zip

**Comment by jason-sachs** [comment]
Please reopen, and provide official Windows release binaries.
