### ISSUE TITLE
Executable name conflict

### ISSUE THREAD

**Issue by thinrope** [google/brotli#594]
Hello,
I just learned about this project, thumbs up!

Unfortunately, the default install produces `/usr/bin/bro` executable and that conflicts with another well-known project [The Bro Network Security Monitor](https://www.bro.org/).

Of course the executable name can be tweaked by each distribution, but I would rather see a change at the source (probably renaming it to `/usr/bin/brotli` ?).
There is one bug already for Gentoo, [#628620](https://bugs.gentoo.org/628620), I guess other distros will pop up...

How do you feel about that?

**Comment by eustas** [comment]
Hello.
 Most distros pick up v0.6 release of brotli, and in this version CLI tool was named "bro". In tip-of-tree version it is "brotli". In one week (hopefully) brotli v1.0 will be released, and distros will start picking up brotli with fixed name.

**Comment by thinrope** [comment]
Great!
(I really hate reporting "fixed-in-master" bugs, apology for that; I only checked the latest release tarball)

**Comment by eustas** [comment]
Absolutely no worries and thanks for the heads-up.
