### ISSUE TITLE
Why "custom dictionary" support was removed?

### ISSUE THREAD

**Issue by Un1oR** [google/brotli#607]
Subj

**Comment by eustas** [comment]
To make API concise and clear for v1.0.0 release.
Internally we are developing a better alternative, and will public it soon.

**Comment by eustas** [comment]
v1.0 means "stable". All the existing API are stable and cover the most useful use-cases.
In future versions (v1.x), we plan to add more functions, but the API that is released in c1.0 will be untouched.

**Comment by KOLANICH** [comment]
Any progress bringing it back?
