### ISSUE TITLE
"Library not found error" with Go bindings

### ISSUE THREAD

**Issue by addityasingh** [google/brotli#609]
While trying to use the Go package `cbrotli`, I was getting error for `File not found` for all the header files `<brotli/encode.h>`, `<brotli/decode.h>`. I fixed this by adding the relative path as below:
```go

#include "../../c/include/brotli/decode.h"

#include "../../c/include/brotli/encode.h"

```

But even after this I get **ld: library not found for -lbrotlicommon** error and have no clue how to fix this. Trying to run the `cbrotli_test.go` throws the same error as shown:

<img width="1105" alt="screen shot 2017-10-08 at 1 46 29 am" src="https://user-images.githubusercontent.com/5351262/31312720-1a67597e-abcb-11e7-94ee-78f69be1c15a.png">

**Comment by eustas** [comment]
Going to dig into this problem soon. What build system do you use?

**Comment by eustas** [comment]
This works for me:
```
mkdir out
cd out
../configure-cmake --disable-debug
cmake ..
make -j8
make test
make install
cd ..
```
After this include/library not found errors do not occur:
```
go build ./go/cbrotli
```

**Comment by addityasingh** [comment]
I will give it a go. Thanks @eustas for the effort 👍

**Comment by addityasingh** [comment]
@eustas Just as a side question, is there any existing usage/example of the `go` implementation somewhere. I tried below but to no avail:
```
godep save github.com/google/brotli/cbrotli
```

> godep: Package (github.com/google/brotli/cbrotli) not found

```
godep save github.com/google/cbrotli
```

> godep: Package (github.com/google/cbrotli) not found

**Comment by eustas** [comment]
I fear, I don't know any.
Going to investigate what is `godep` soon =)

**Comment by eustas** [comment]
Even if `godep save` would finish successfully, it seem that it wouldn't work anyways: https://github.com/tools/godep/issues/422

**Comment by eustas** [comment]
Merging with similar issue #585
