### ISSUE TITLE
bootstrap uses arithmetic not available in plain sh

### ISSUE THREAD

**Issue by Sp1l** [google/brotli#622]
https://github.com/google/brotli/blob/0ad94eed00420bf1154cb16a289aa27efbb30c01/bootstrap#L1

Even though the shebang indicates this uses plain shell, it uses arithmetic not available in plain shell.
Hard depending on bash would make sense here (though zsh works as well).

**Comment by eustas** [comment]
Thanks for the report. Going to switch to plain shell + expr. Will it be better?
