### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by zamazan4ik** [google/brotli#624]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by eustas** [comment]
Hello. Will gladly do this, when I have spare cycles =)

**Comment by mikroskeem** [comment]
Any update on this?

**Comment by eustas** [comment]
Hi. Sorry, haven't had time for this yet =(

**Comment by mikroskeem** [comment]
ETA? :smile:

**Comment by andreas-ibm** [comment]
Think you can close this since it's available at https://conan.io/center/brotli :-)
