### ISSUE TITLE
libbrotlienc.so and libbrotlidec.so should both require libbrotlicommon.so

### ISSUE THREAD

**Issue by rcanavan** [google/brotli#634]
both libbrotlidec and libbrotlienc use BrotliGetDictionary from libbrotlicommon, but rely on the binary using brotli to also load libbrotlicommon. It may be more convenient for end users to link the enc and dec libraries against libbrotlicommon.so. The mod_brotli included in apache httpd 2.4.29 does not automatically pick up this dependency, and as a consequence, build a mod_brotli that can only be used by LD_PRELOADind libbrotlicommon.so. 

Proposed patch:
```--- Makefile.am 2018-02-02 14:04:26.544647322 +0100
+++ ../brotli-1.0.2-autoconf/Makefile.am        2018-02-02 13:51:24.773377900 +0100
@@ -22,9 +22,9 @@
 libbrotlicommon_la_SOURCES = $(BROTLI_COMMON_C) $(BROTLI_COMMON_H)
 libbrotlicommon_la_LDFLAGS = $(AM_LDFLAGS) $(LIBBROTLI_VERSION_INFO) $(LDFLAGS)
 libbrotlidec_la_SOURCES = $(BROTLI_DEC_C) $(BROTLI_DEC_H)
-libbrotlidec_la_LDFLAGS = $(AM_LDFLAGS) $(LIBBROTLI_VERSION_INFO) $(LDFLAGS) -lbrotlicommon
+libbrotlidec_la_LDFLAGS = $(AM_LDFLAGS) $(LIBBROTLI_VERSION_INFO) $(LDFLAGS)
 libbrotlienc_la_SOURCES = $(BROTLI_ENC_C) $(BROTLI_ENC_H)
-libbrotlienc_la_LDFLAGS = $(AM_LDFLAGS) $(LIBBROTLI_VERSION_INFO) $(LDFLAGS) -lbrotlicommon
+libbrotlienc_la_LDFLAGS = $(AM_LDFLAGS) $(LIBBROTLI_VERSION_INFO) $(LDFLAGS)
 
 pkgconfigdir = $(libdir)/pkgconfig
 pkgconfig_DATA = \
```

**Comment by rcanavan** [comment]
That patch is obviously rubbish and fails when building in parallel. My understanding is that a proper solution would require the libraries to be separated into separate directories.

**Comment by eustas** [comment]
Doesn't `libbrotlidec_la_LIBADD = libbrotlicommon.la -lm` and `libbrotlienc_la_LIBADD = libbrotlicommon.la -lm` do that?

**Comment by eustas** [comment]
Oh, it is not in 1.0.2! Going to release 1.0.3 very soon.

**Comment by rcanavan** [comment]
> Doesn't libbrotlidec_la_LIBADD = libbrotlicommon.la -lm and libbrotlienc_la_LIBADD = libbrotlicommon.la -lm do that?

it does. Those two changes on top of 1.0.2 work flawlessly for me. Thanks.
