### ISSUE TITLE
How to use large window sizes?

### ISSUE THREAD

**Issue by JiMMYBOOi** [google/brotli#639]
I built brotli using the latest sources, but the window size is limited to 16mb. How do I set it to larger window sizes like 512mb?

**Comment by eustas** [comment]
Hello.

Currently we are testing "Large Window Brotli" extension that will allow up to 1GiB window.
Hopefully, it will be published this week.

**Comment by JiMMYBOOI** [comment]
can I make any trade-offs to improve ratio?

**Comment by eustas** [comment]
"Large Window Brotli" is landed.

We constantly work to make quality=11 denser. You could play with some internal constants, but, most likely they won't provide big improvement.

To give a more specific advice, I have to know the use case...
