### ISSUE TITLE
 java.lang.UnsatisfiedLinkError: org.brotli.wrapper.enc.EncoderJNI.nativeCreate([J)Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by vaneri** [google/brotli#641]
Hello, 

Here are the steps that I did so far:
- CMAKE => /out/ folder has been created with an /out/installed folder containing the result of the installation
- cp -r /out/install /usr/
supposedly adding all the libraries in the path that can be discovered

As this was not working and I was getting the exception UnsatisfiedLinkError; I tried the following:

Loading individually the libraries:
System.load(new java.io.File("/usr/lib/libbrotlicommon.so").getAbsolutePath());
System.load(new java.io.File("/usr/lib/libbrotlidec.so").getAbsolutePath());
System.load(new java.io.File("/usr/lib/libbrotlienc.so").getAbsolutePath());

This didn't help either.

I try to change the path java.library.path and use the /usr/lib but this didn't help either.

Do you have any clue on what I am doing wrong in the JNI loading?
I am using :
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.4 LTS
and 
IntelliJ IDEA as IDE

Thanks

**Comment by eustas** [comment]
Hello.

 JNI wrappers are currently not supported in CMake build.
 You could try using Bazel: `bazel build -c opt java/org/brotli/wrapper/...:all`, or pick up prebuilt artifacts from [bintray](https://bintray.com/eustas/brotli/bin/snapshot/view/files) (only for windows)

**Comment by vaneri** [comment]
Thanks for the information; could you tell me more about the bazel output; is it only working for windows?
What shall I suppose to do with the output? what jar/file should I use/copy?

Thanks a lot for your help,
Rimbaud

**Comment by eustas** [comment]
".dll" is the file suffix. Actually when project is built under mac / linux it produces valid shared library (those systems are less picky about filename suffix). Anyways, produced artifact could be renamed...

**Comment by eustas** [comment]
Although, it is always better to make a custom build and have a single library for all the native deps of the app, if possible.

FWIW, jni library for windows is published on bintray after successful Appveyor builds; perhaps this will be also useful for OSX, but not for linux (due to fragmentation).
