### ISSUE TITLE
command line argument for custom dictionary

### ISSUE THREAD

**Issue by jendap** [google/brotli#658]
Should brotli command line tool have a flag to use custom dictionary? One can build it (with some effort of compiling stand alone tool) and then what? Writing custom tool to use it?

(one could easily write a test script to see potential of shared dictionary)

BTW: Can also "brotli --help" mention existence of "--large_window" flag?

**Comment by eustas** [comment]
Hello.

  Custom dictionaries are supported by "shared-brotli" (see corresponding branch). Soon "shared-brotli" will be merged to master branch.

Perhaps "brotli --verbose --help", because currently this option is not widely advertised, to avoid misusage of this option.

**Comment by jendap** [comment]
Thank you, Eugene!

Ok, the shared brotli with custom dictionary does good job. Thanks!

Just put the long_window into normal help. People who want to shoot themselves will always manage to do so. Just put there warning that it is usually not good idea.
