### ISSUE TITLE
New benchmarks?

### ISSUE THREAD

**Issue by bknowles** [google/brotli#673]
Might I also suggest linking to the following additional benchmark pages?  See:

https://www.opencpu.org/posts/brotli-benchmarks/
https://community.centminmod.com/threads/compression-comparison-benchmarks-zstd-vs-brotli-vs-pigz-vs-bzip2-vs-xz-etc.12764/

**Comment by servermeta** [comment]
Is benchmark part of testing? 

I just noticed a regression in file size from Ubuntu 17.10 (brotli 0.6.0) and the git repo (brotli 1.0.4).

With more recent brotli version file size is bigger, and the LZ77 window size is almost always non optimal.

**Comment by eustas** [comment]
We check how our changes affect density/performance. It is quite possible that improvements on one dataset might be disadvantageous to other. Personally I liked https://github.com/quixdb/squash-benchmark project, but it seems to be dead nowadays.
