### ISSUE TITLE
MSVC C4551 compiler warnings in platform.h

### ISSUE THREAD

**Issue by rvandermeulen** [google/brotli#678]
I was taking a look at updating Firefox' vendored copy of brotli to version 1.0.4 today.

Along the way, I ran into Werror bustage in platform.h within the newly-added `BROTLI_UNUSED_FUNCTION void BrotliSuppressUnusedFunctions(void)` block. MSVC gives a "warning C4551: function call missing argument list" error for each subsequent line within it.

The warning is fixable by explicitly making those all references instead, i.e. `BROTLI_UNUSED(&BrotliSuppressUnusedFunctions)` instead of `BROTLI_UNUSED(BrotliSuppressUnusedFunctions)`. As far as I can tell, everything compiles and functions fine with GCC and clang as well with this change.

**Comment by eustas** [comment]
Going to do that soon. Thanks for reporting.
