### ISSUE TITLE
fuzz directory to have C sources instead of C++

### ISSUE THREAD

**Issue by kasper3** [google/brotli#681]
ref https://github.com/dotnet/corefx/issues/30249
We are in process of converting some C++ sources in corefx and found that `fuzz` directory, that lives under `c` has two `c++` sources https://github.com/google/brotli/tree/8544ae858d87056c8dac55713ffe148d9c60eb93/c/fuzz. Could these two `.cc`'s be updated to `C`?

**Comment by eustas** [comment]
I'll check in on Monday. Alternatively, it could be moved from c/fuzz, to fuzz/ or somewhere else.

**Comment by kasper3** [comment]
Thanks @eustas. I have sent a PR to purge C++'ism from fuzz https://github.com/google/brotli/pull/682. However, I don't have Google Account to account the CLA with. Feel free to use this patch as a public domain contribution. :)

**Comment by kasper3** [comment]
@eustas, have you had a chance to look at it?

**Comment by kasper3** [comment]
Fixed by #686.

**Comment by eustas** [comment]
Release is postponed a little bit; oss-fuzz failed to build the new binary (clang++ said that it does not like std=c99, and then clang failed to link with c++ fuzzer library)... Hopefully all things will work together on this weekend -> v1.0.5 will be released on Monday.
