### ISSUE TITLE
Brotli decompressor doesn't work on Visual C++ 2017 compiled with full optimizations

### ISSUE THREAD

**Issue by jhudsoncedaron** [google/brotli#684]
I extracted the decoder (by copying whole files), wrapped the stuff into a .dll, and built it with Visual C++ 2017 targeting x64. The decoder doesn't copy anything into its output file if the .dll is compiled with full optimization, but works just fine if I disable optimization.

I don't even know how to begin tracking this down. It could easily be a bug in brotli (which I would be much more certain of if this were gcc) or in Visual Studio. I could bisect which compiler optimization option causes this but I really don't think that's going to help.

Current git hash of brotli is 09cd3e877f583e6352be146ab22415298366c8d6

**Comment by eustas** [comment]
Going to try to reproduce next week.

**Comment by eustas** [comment]
Going to add VS2017 x64 debug and release builds to Appveyor matrix soon to see if it works.

**Comment by jhudsoncedaron** [comment]
I have bisected the triggering compiler option. The one that breaks it is /NODEFUALTLIB. This makes trying the CMake project pointless.

Turning off optimizations makes it go away, but turning on optimizations and still linking against MSVC*.dll results in a working binary as well. The fault is occurring where the compiler tries to inline memcpy.

The current optimizations are: /O2 /Ot /GL /GS- /Gy  /sdl- /NODEFAULTLIB

**Comment by jhudsoncedaron** [comment]
Nevermind. I messed up memcpy pretty bad. I'm shocked it worked with optimizations off.
