### ISSUE TITLE
Decompress truncated files

### ISSUE THREAD

**Issue by alberto-esposito** [google/brotli#689]
Mine might be an edge case, but I need to decompress truncated files.

I'm testing http2 chunked responses, with precompressed files.

Currently, with gzip I calculate optimal truncation points by trial and error, trying several combinations until I find the best one.

With Brotli I can't do it from the command line and thus I can't automate it. From the browser it works, though.

reproduction:

`brotli input.txt && truncate -s700 input.txt.br && brotli -d input.txt.br`

**Comment by eustas** [comment]
Hello.

 Could you elaborate, please? What are "optimal" truncation points?

 Brotli decoder is built in a way to decode all the input bytes it has been provided so far. Every "flush" will add overhead, and is only useful for dynamic packaged networking, where it is important to give guarantees that all the encoded bytes will be decoded on the other size (i.e. nothing is "buffered")...

**Comment by eustas** [comment]
You could use Python wrapper. It's API is close to C API, but allows quick experiments.
