### ISSUE TITLE
dictionary.bin.br in source tree

### ISSUE THREAD

**Issue by kasper3** [google/brotli#692]
Is this file needed or mistakenly checked in:
https://github.com/google/brotli/blob/b601fe817/c/common/dictionary.bin.br

**Comment by eustas** [comment]
No, this file is checked in intentionally. This is a brotli RFC dictionary compressed without using brotli RFC dictionary.
So it is possible to get dictionary-less brotli decoder, decode this file, supply result to decoder to obtain fully-featured decoder.

**Comment by kasper3** [comment]
Thanks, it makes sense.
