### ISSUE TITLE
Potential "Control flow issues" detected by Coverity

### ISSUE THREAD

**Issue by sylvestre** [google/brotli#696]
Updating to [brotli 1.0.5 in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1474122), coverity discovered two new issues (CID 1437666 & 1437667)

For 
https://github.com/google/brotli/blob/master/c/enc/hash_rolling_inc.h#L131
Coverity says: 

> dead_error_condition: The condition (position & 0UL) != 0UL cannot be true.

And for 
https://github.com/google/brotli/blob/master/c/enc/hash_rolling_inc.h#L164

> dead_error_condition: The condition (cur_ix & 0UL) != 0UL cannot be true.

As they do not seem to be false positive, I prefer to report them!

**Comment by eustas** [comment]
Those are, actually, false-positives. https://scan.coverity.com/projects/google-brotli/view_defects
Coverity Scan, unfortunately, does not understand the concept of C89 templates.
Compiler will remove those pieces where they are really always-true, no need to worry about that.

**Comment by sylvestre** [comment]
OK, sorry!

**Comment by eustas** [comment]
No worries. Thanks for the heads-up!
