### ISSUE TITLE
JavaScript encoder script

### ISSUE THREAD

**Issue by SuperPat45** [google/brotli#700]
Please add a encoder script in JavaScript.

I will need to compress a text/csv file before upload to save bandwidth on mobile devices

**Comment by eustas** [comment]
Hello. Unfortunately we do not have time now to produce high-quality JavaScript encoder =(
But you can try to use `emscripten` to compile c to JS.
Even better - there is an NPM package that contains emscriptified brotli encoder: https://www.npmjs.com/package/brotli

**Comment by eustas** [comment]
Will be resolved once we have pure-java encoder (== not soon).
