### ISSUE TITLE
Question about brotli compression

### ISSUE THREAD

**Issue by HiitLee** [google/brotli#711]
I am a student  at Kookmin Univ in Korea.

I want to introduce your brolit compression algorithm.

So, I saw your paper as name is "Brotli Compressed Data Format".

But I do not understand it well in my thesis.

If possible, I am wondering if you can send me the ppt you wrote when you made the announcement or the summarized.

I heard that your algorithm is the best now, and I would like to introduce it to our studnets.

Thank you so much.

**Comment by eustas** [comment]
Hi. Not sure if I understood the question correctly.
Here is RFC that describes the file format: https://tools.ietf.org/html/rfc7932
Here is an article, that compares brotli to other formats: https://github.com/google/brotli/blob/master/docs/brotli-comparison-study-2015-09-22.pdf

Unfortunately, the internals of brotli encoder are not described in any article; on the bright side, brotli encoder is built on the base of widely used algorithms:
 * [hash table](https://en.wikipedia.org/wiki/Hash_table) for finding backward references
 * [binary search tree](https://en.wikipedia.org/wiki/Binary_search_tree) as an alternative way looking for backward references
 * [dynamic programing](https://en.wikipedia.org/wiki/Dynamic_programming) for optimizing copy-insert sequence
 * [priority queue](https://en.wikipedia.org/wiki/Priority_queue) for gradual histogram clustering
