### ISSUE TITLE
v1.0.7 tag still have old 1.0.6 number in version.h 

### ISSUE THREAD

**Issue by anthrotype** [google/brotli#720]
https://github.com/google/brotli/blob/master/c/common/version.h#L17

I noticed when attempting to build new python wheels from the v1.0.7 tag. 
The name of the wheel is the same as the previous one bearing version 1.0.6, and thus it can't be deployed to PyPI:
https://travis-ci.org/google/brotli-wheels/jobs/445027040#L593

I suggest deleting the tag, fixing up the version string and tagging again.

**Comment by eustas** [comment]
Ooops. Thanks for the heads-up.

**Comment by anthrotype** [comment]
thanks, it should be fixed now
