### ISSUE TITLE
Where can I find the apache module

### ISSUE THREAD

**Issue by maniac0s** [google/brotli#723]
Sorry https://httpd.apache.org/docs/trunk/mod/mod_brotli.html brought me here, now I am browsing the internet like an imbecile and cant find the module anywhere

**Comment by eustas** [comment]
https://github.com/apache/httpd/blob/trunk/modules/filters/mod_brotli.c ?

**Comment by XPanniX** [comment]
Stumbled upon this after browsing the web like @maniac0s.  
  
I just wanted to clarify how to get the Brotli module working in Apache2 (Version >=2.4.26) for anyone having the same problem. Apparently all you need to do is:

    a2enmod brotli
