### ISSUE TITLE
brtotli command line tool: list option

### ISSUE THREAD

**Issue by stokito** [google/brotli#726]
gzip tool provides an option to list the archive contents:
```
l, --list        list compressed file contents
```
This is useful for archive managers like engrampa to let us known the uncompressed size.
For example if archiver doesn't support the list function then it needs for a workaround:
https://github.com/mate-desktop/engrampa/blob/master/src/fr-command-cfile.c#L158

Could you implement the similar option?

**Comment by eustas** [comment]
Surely, but a little bit later.

**Comment by eustas** [comment]
Brotli is a "stream" format, so it does not keep original filename & modification time (unlike gzip).
Future "brotli-framing-format" allows storing this metadata + other cool stuff.
