### ISSUE TITLE
`brotli --test --verbose` should show a message

### ISSUE THREAD

**Issue by stokito** [google/brotli#729]
When running a integrity test brotli shows nothing and t his is correct according to unix philosophy.
But when I asked the brotli to be verbose it still didn't show anything:
```
$ brotli -vt goodarchive.br
$ brotli -vt corrupt.br
corrupt input [corrupt.br]
```
What do I expect is the same behavior as for `gzip`, `xz` and many other compressors:
```
$ gzip -vt goodarchive.gz
goodarchive.gz:	 OK
$ gzip -vt corrupt.br
gzip: corrupt.gz: not in gzip format
```

As you can see in verbose mode test shows a file name and status OK.

Could you make brotli to work similar with other compressors?

**Comment by eustas** [comment]
Surely. Will implement that soon (when get some free cycles =)

**Comment by stokito** [comment]
@eustas  thank you. Also please note that gzip, uncompress, bzip2, lzip, lzma, xz, lzop compressors usually prints an output to `stderr` instead of `stdout` but `rar` and `7zip` prints to `stdout`.
So I'm not sure what is a correct behavior but please implement according to some standard de-facto i.e. stderr.

**Comment by eustas** [comment]
I think it is fixed now:
```
 ~$ brotli -tv gato.html.br 
Decompressed [gato.html.br]: 698 B -> 4.395 KiB
```
