### ISSUE TITLE
C++ compilation fails without -fpermissive

### ISSUE THREAD

**Issue by very-cool-name** [google/brotli#731]
Hello! Is there a specific reason why this character array implemented with explicit '\0' in the end?

https://github.com/google/brotli/blob/5805f99a533a8f8118699c0100d8c102f3605f65/c/common/transform.c#L14

It fails to compile on C++ compiler with error:
`error: initializer-string for array of chars is too long [-fpermissive]`

Is it possible to write it without specifying size? I.e. :
`static const char kPrefixSuffix[] = "...."`

I've looked at disassembled code https://godbolt.org/z/cwc5Xi and don't see much difference, except copying from register.

**Comment by very-cool-name** [comment]
Or if for some reason number 217 is necessary, you can use array initialization:
`static const char kPrefixSuffix[217] = {'\1', ' ', '\2', ',', ' '}`
tedious, but you have to write it only once.

**Comment by eustas** [comment]
Luckily, the last character is `\0`. We can just remove it... Will fix very soon.

**Comment by eustas** [comment]
Will be fixed with #749
