### ISSUE TITLE
bootstrap fails on CentOS 6

### ISSUE THREAD

**Issue by jamesjer** [google/brotli#732]
I downloaded the brotli 1.0.7 release on a CentOS 6 box and unpacked it.  This box has autoconf 2.63.  Then:

```
[brotli-1.0.7]$ ./bootstrap
/usr/bin/m4:configure.ac:4: Warning: too few arguments to builtin `m4_index'
/usr/bin/m4:configure.ac:4: bad expression in eval (bad input): 0m4_warn([syntax], [AC_INIT: not a literal: https://groups.google.com/forum/#!forum/brotli])
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1
./bootstrap: line 31: exit: $: numeric argument required
```

Double quoting the URL fixes the problem; i.e., change line 4 of configure.ac to read:

```
AC_INIT([brotli], [1.0.7], [[https://groups.google.com/forum/#!forum/brotli]])
```

**Comment by eustas** [comment]
Will fix soon. Thanks for the report.

**Comment by eustas** [comment]
Interesting, autoconf have had a regression between 2.66 and 2.68 for "?" in urls... But 2.63 is even older and might be more buggier =)

**Comment by eustas** [comment]
No response. Closing for now. Feel free to reopen (with the answer to the last question).
