### ISSUE TITLE
libbrotli jni header

### ISSUE THREAD

**Issue by enexusde** [google/brotli#734]
I need to compress in java.

The problem: There is no fast encoder in java.
The idea: Native bind libbrotli to java using JNI. Publish the Java-Class in github.

Example:

Write class: 
```package com.google.brotli;
public class BrotliEncoder {
  public native byte[] encode(byte[] uncompressed, Charset uncompressedEncoding);
}
```
call javah to create `com_google_brotli_BrotliEncoder.h`

```
#include <jni.h>
#ifndef _Included_com_google_brotli_BrotliEncoder
#define _Included_com_google_brotli_BrotliEncoder
#ifdef __cplusplus
extern "C" {
#endif
JNIEXPORT jbyteArray JNICALL Java_com_google_brotli_BrotliEncoder_encode
  (JNIEnv *, jobject, jbyteArray, jobject);
#ifdef __cplusplus
}
#endif
#endif
```
Implement the header in libbrotli

**Comment by eustas** [comment]
I believe https://github.com/google/brotli/tree/master/java/org/brotli/wrapper/enc is exactly what you want =) Especially Encoder.compress (see https://github.com/google/brotli/blob/master/java/org/brotli/wrapper/enc/Encoder.java#L202)

**Comment by enexusde** [comment]
Looks good.
