### ISSUE TITLE
Question: How to use Br decode.js ?

### ISSUE THREAD

**Issue by pencil240** [google/brotli#738]
Is there a demo for the decode.js  in the page : https://github.com/google/brotli/tree/master/js  ?
Will the br's js version be the official version?

The other project for br decode has not been updated for many years, there were some issues still in open status:    https://github.com/foliojs/brotli.js/issues/24

**Comment by eustas** [comment]
Hello. Yes, this is "official". It is transpiled from Java decoder and will get all its features.
Some speedups are already in internal repo and not yet published; large window and dictionary support is also on the way to release =)

Usage example could be seen in test code: https://github.com/google/brotli/blob/master/js/decode_test.js

Also internally we have CLI wrapper for node.js, but it is not release quality, and mostly used for testing...
