### ISSUE TITLE
Provide slimmer release source tarballs 

### ISSUE THREAD

**Issue by felixbuenemann** [google/brotli#747]
Currently to build libbrotli or the brotli cli one has to pull down a huge 23 MB tarball, even though only the build scripts (Makefile etc.) and "c" subdirectory are required for compilation, which account to ~550 KB gzipped.

It would be great if the releases tab could provide downloads for slimmer tarballs that only contain the required files.

I'd be happy to create a PR that adds a make target to create a release tarball.

**Comment by eustas** [comment]
Will try to do that soon.

**Comment by eustas** [comment]
Can't find any filtering setting.
The only option seems to create more artefacts on "before_deploy" stage in travis and publish them.
And the remove "fat" tarballs manually...

**Comment by eustas** [comment]
It seems there is a solution. There is a speculation that GitHub uses `git archive` and thus we can tune the archive content by hacking `.gitattributes`. Going to try that.
Perhaps will leave only C code, as other languages have standartized package / distribution systems.

**Comment by eustas** [comment]
Yay, it works. zip file for the next release will be ~525kb =)

**Comment by felixbuenemann** [comment]
Nice trick!
