### ISSUE TITLE
-q option is redundant and incompatible with other compression programs

### ISSUE THREAD

**Issue by planet36** [google/brotli#757]
$ brotli --version
brotli 1.0.7

As described in the help message, the -q option seems to do almost the same thing as the -# option.  I know that compression levels 10 and 11 are not possible with the -# option.
>   -#                          compression level (0-9)
>   -q NUM, --quality=NUM       compression level (0-11)

The following compression programs use the -q option to make the program "quiet".
- bzip2
- clzip
- gzip
- lbzip2
- lz4
- lzip
- lzop
- minilzip
- pbzip2
- pdlzip
- pigz
- plzip
- xz
- zstd

This prevents brotli from being a drop-in replacement for other compression programs.

**Comment by eustas** [comment]
Unfortunately, it is too late. Removing `-q` will harm existing users.
On the other side, it is not terribly difficult to write a wrapper script that would eat `-q` and pass other parameters as is to brotli executable.
