### ISSUE TITLE
Please bundle LICENSE/NOTICE files in the produced jar files

### ISSUE THREAD

**Issue by vlsi** [google/brotli#758]
It would be nice if you could add LICENSE to META-INF/LICENSE , so the license could be automatically discovered.

Clarification: brotli license enforces re-distributions to reproduce license text, and it is hard to tell which license text should be associated with the jar since the text might vary over time.

The ...jar is often re-distributed via Maven dependency, thus it becomes complicated to automatically re-distribute the proper LICENSE file since Maven Central misses that file.

Solution: include META-INF/LICENSE into the generated jar file. You might want to optionally include META-INF/NOTICE as well

**Comment by eustas** [comment]
Fixed
