### ISSUE TITLE
Test vectors of 'asyoulik.txt' and 'asyoulik.txt.compressed' are not aligned each other

### ISSUE THREAD

**Issue by eugeneilyin** [google/brotli#763]
The compressed version of [asyoulik.txt.compressed](https://github.com/google/brotli/blob/master/tests/testdata/asyoulik.txt.compressed)  after decompression gives `asyoulik.txt` with `LF` (ASCII 0x0A) line separators.

But the original file [asyoulik.txt](https://github.com/google/brotli/blob/master/tests/testdata/asyoulik.txt) contains `CR LF` (ASCII 0x0D 0x0A) line separators. 

Please update the compressed version `asyoulik.txt.compressed` to contain original with `CR LF` separators as it's presented in other text samples.

**Comment by eustas** [comment]
Does that happen with clean checkout after #761?

**Comment by eugeneilyin** [comment]
@eustas, I see that test vectors were changed. The compression/decompression checks with all levels of `Quality` and `WindowBits` were passed on all new samples. This issue can be closed. Thanks for the fix.
