### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [google/brotli#779]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by Jas0n99** [comment]
Perhaps the multithreaded code get added in before the next release version, even if that feature is marked experimental. I saw eustas made some comments in other queries that it should be easy to implement now.

**Comment by victorstewart** [comment]
so it's still the intention that use the 2018 release instead of compiling the master branch right?

**Comment by kloczek** [comment]
Now after release year ago 1.0.9 and closing that ticket IMO it would be good to make another release (1.0.10?) :)

**Comment by eustas** [comment]
Moved to umbrella #1056
