### ISSUE TITLE
Null deference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [google/brotli#789]
There is no check for the failed malloc
https://github.com/google/brotli/blob/ee2a5e1540cbd6ef883a897499d9596307f7f7f9/c/fuzz/run_decode_fuzzer.c#L29

This in turn would cause a segfault， when buff is dereferenced
https://github.com/google/brotli/blob/ee2a5e1540cbd6ef883a897499d9596307f7f7f9/c/fuzz/run_decode_fuzzer.c#L30

**Comment by eustas** [comment]
This code is never executed - it is just a toy to check that fuzzer could be compiled. Will fix when get few free cycles.
