### ISSUE TITLE
Weird name in Java pom

### ISSUE THREAD

**Issue by rubengees** [google/brotli#800]
The [pom](https://repo1.maven.org/maven2/org/brotli/parent/0.1.2/parent-0.1.2.pom) of `brotli-java` is having this name in it: 

```
<name>${project.groupId}:${project.artifactId}</name>
```

I guess that's not intended. Can that be changed?

**Comment by eustas** [comment]
Not sure, but it seem to be somehow related to publishing library to maven repo: https://github.com/google/brotli/pull/514/files

**Comment by beppo-sturmtief** [comment]
Hi, i presume this is intended - that syntax uses maven properties of the project and the maven build will replace those values accordingly. Specifically these are the maven group id (derived as "org.brotli" from the parent pom) and artifact id ("dec") resulting in "<name>org.brotli:dec</name>". 

I guess this would be a non-issue or can be closed

**Comment by beppo-sturmtief** [comment]
Hi, i presume this is intended - that syntax uses maven properties of the project and the maven build will replace those values accordingly. Specifically these are the maven group id (derived as "org.brotli" from the parent pom) and artifact id ("dec") resulting in "<name>org.brotli:dec</name>". 

I guess this would be a non-issue or can be closed

**Comment by beppo-sturmtief** [comment]
Hi, i presume this is intended - that syntax uses maven properties of the project and the maven build will replace those values accordingly. Specifically these are the maven group id (derived as "org.brotli" from the parent pom) and artifact id ("dec") resulting in "<name>org.brotli:dec</name>". 

I guess this would be a non-issue or can be closed
