### ISSUE TITLE
Get Serialized state of the dictionary 

### ISSUE THREAD

**Issue by IhsenCharfi** [google/brotli#801]
Hey , I want to use brotli for stream compression in a go lang project.

I have a use case when i need to send compressed data between tcp server/client. I want to  get a serialized state of the dynamic dictionary created to exchange msg between client and server. So that, after, I will be able to de save the state and continuen using the dictionary created for further compression.

Is this feature/api available within this library ?

If no, I want to add it to this library, so from where should I start ? Can you give me some hints ?

Are you interested in this use case to add it to the library ?

**Comment by eustas** [comment]
Brotli is build on LZ77 ideas. Unlike LZ78 / LZW there is no "dictionary" built in the process of compression. The input data is a source of references (implicit dictionary). To improve compression there is a way to "virtually" prepend some data. Please see `-D` CLI option, and `Brotli*Dictionary*` methods documentation.
