### ISSUE TITLE
platform.h (lines 552-553): _BitScanReverse

### ISSUE THREAD

**Issue by dejanyy** [google/brotli#811]
On lines 552-553 of platform.h we have:

uint32_t msb;
_BitScanReverse(&msb, x);

I think "uint32_t msb;" is wrong. Certainly doesn't compile with MS Visual Studio 2017. Changing that line to "unsigned long msb;" seems to fix the problem. See:
https://docs.microsoft.com/en-us/cpp/intrinsics/bitscanreverse-bitscanreverse64?view=vs-2019

**Comment by eustas** [comment]
Indeed! I believe it is compiled in CI  only by an accident (when `uint32_t` is the same type as `unsigned long`).
Going to fix soon. Thanks for the report!
