### ISSUE TITLE
Recommended sizes for input/output buffer + compressor/decompressor

### ISSUE THREAD

**Issue by andrew-aladev** [google/brotli#816]
Hello. zstd has the [following functions](https://github.com/facebook/zstd/blob/dev/lib/zstd.h#L778-L779) available:

```c
size_t ZSTD_CStreamInSize(void);    /**< recommended size for input buffer */
size_t ZSTD_CStreamOutSize(void);   /**< recommended size for output buffer. Guarantee to successfully flush at least one complete compressed block. */

size_t ZSTD_DStreamInSize(void);    /*!< recommended size for input buffer */
size_t ZSTD_DStreamOutSize(void);   /*!< recommended size for output buffer. Guarantee to successfully flush at least one complete block in all circumstances. */
```

It will be good to have similar functions for brotli.

For now i am using `256/64 kb` for compressor and `64/256 kb` for decompressor.

**Comment by eustas** [comment]
Both encoder and decoder are just fine with any input buffer, the bigger - the better. 
As for output I recommend "zero-copy" API (`*TakeOutput`) it already uses optimal buffer internally.
