### ISSUE TITLE
Release compilation by default

### ISSUE THREAD

**Issue by riknel** [google/brotli#817]
Hello! 
You have a debug version of compilation by default. Wouldn’t it be better if you have a faster(release) version by default?
My concerns are that some developers may not notice the flag for release built and will use subpar Brotli for their compression. I haven’t noticed it at first but speaking with Jyrki Alakuijala helped. I also know that some other people have missed this flag.

**Comment by eustas** [comment]
Hello.
Which build system you are referring to? `make` / `automake` / `Bazel` / `Premake` / `CMake`?

The most popular is `CMake`, and in the readme we explain how to build "Release" version.

Fixing "Release" for `Bazel` is an anti-pattern.

`make` is not properly supported as a build system in this repository, as it does not have "configuration" phase.

`automake` has one; but it builds "Release" version by default IIRC; and `Premake` too.

**Comment by riknel** [comment]
Mostly about Cmake as usually people use it. 
Yes, I've seen that you have an explanation on how to do a release built for Cmake. What I meant is it seems like some people have missed this explanation and used a debug version instead (me and some other people I spoke to). If those people use Brotli for production purposes it may have a huge drop in performance. So I think it's better if the default version would be a release one. What do you think?
