### ISSUE TITLE
Which webcrawlers do not support brotli?

### ISSUE THREAD

**Issue by dilyanpalauzov** [google/brotli#821]
I find no better place to ask: 

Which webcrawlers (search engines) do support brotli and which not?  If sitemap.xml is br and gz compressed, will the gz file ever be fetched?  If the target browsers all support brotli, has the website content to be in addition gzip compressed, in order to speed the webcrawlers?

**Comment by dilyanpalauzov** [comment]
Yandex does not support Brotli, but gzip and deflate.

**Comment by eustas** [comment]
I believe https://groups.google.com/g/brotli is the best place for discussions.
