### ISSUE TITLE
Is there any python documentation? 

### ISSUE THREAD

**Issue by mlissner** [google/brotli#822]
I've looked around a bit, but aside from install directions, there doesn't seem to be any python documentation. I'd be happy to update the readme with some information. Just a simple...

 - This is how you compress
 - This is how you decompress

...would be helpful. 

Is this written down anywhere? Also, is the python API stable? Often when it's not documented, it shouldn't be trusted?

**Comment by eustas** [comment]
Tests are the best documentation =) API is stable and hasn't changed since its initial publication.
PRs that improve the textual documentation are welcome.
