### ISSUE TITLE
sources.lst absent

### ISSUE THREAD

**Issue by jengelh** [google/brotli#828]
https://github.com/google/brotli/archive/v1.0.8rc.tar.gz
md5sum  ef418129d5a3d42866e061fdbd600543

Even though this archive is supposedly generated from commit 665e81d (says github tag page), the tarball does not include "sources.lst", causing autotools/cmake to fail to run.

**Comment by eustas** [comment]
Hello. Thanks for the reports.
Working on it. Few more important files are also missing.

**Comment by eustas** [comment]
Fixed in v1.0.8rc2
