### ISSUE TITLE
Python bindings for 1.0.8

### ISSUE THREAD

**Issue by dvershinin** [google/brotli#830]
Wondering why `setup.py` and `python` directory is missing in the 1.0.8 release tarball?

**Comment by eustas** [comment]
Python bindings are released via https://github.com/google/brotli-wheels
Will be done very soon.

**Comment by eustas** [comment]
Please take a look at https://pypi.org/project/Brotli/#files
Is `Brotli-1.0.8.zip` what you were looking for?

**Comment by dvershinin** [comment]
Yes, that is the thing I'm looking for. But I'm still wondering why the release tarball is here is a "stripped down" version of the actual files on that tag.

Now in order to build an RPM package have to fetch the zip from PyPi whereas before things were readily available from the release tarball here.

**Comment by eustas** [comment]
Sorry about that. Earlier we had an issue where developers asked for slimmer tarball (it was 15MiB IIRC).

Surely, we could put some files back, just name them!

**Comment by dvershinin** [comment]
I think at least `setup.py`, `setup.cfg` and `python` dir should make it back to the release tarball.

The rationale is that this would allow building RPMs for the Python bindings as soon as the new Brotli release is tagged.

**Comment by eustas** [comment]
Should be fixed now
