### ISSUE TITLE
1.0.9: cmake dioes not install man pages lvl 3

### ISSUE THREAD

**Issue by kloczek** [google/brotli#832]
Just checked 1.0.9 and looks like cmake does not install man devel man pages.

**Comment by eustas** [comment]
There are 5 changes to CMakeLists.txt since 1.0.7
Investigating

**Comment by eustas** [comment]
v1.0.7 has the same behaviour

**Comment by eustas** [comment]
History show it never did.

**Comment by eustas** [comment]
Duplicate of #756
