### ISSUE TITLE
Window.BrotliDecode is not set in decode.min.js

### ISSUE THREAD

**Issue by mrpmorris** [google/brotli#844]
The minimised version of decode.js sets
```
window.ra=BrotliDecode;
```
when it sould set
```
window.BrotliDecode = BrotliDecode;
```

**Comment by eustas** [comment]
Hi. In your comment strings only differ by the semicolon.

Though, "min" version looks strange: "BrotliDecodeClosure" is not shortened, and "ra" should be "BrotliDecode".
Going to revise that soon.

**Comment by mrpmorris** [comment]
@eustas sorry, text was wrong. I've now corrected it

**Comment by guardrex** [comment]
Hello ...

May I inquire on a status update given that no labels have been applied to indicate when/if this might be worked?

We (MS docs) must indicate to developers to use the unminified script until this is addressed. If the thinking is that this will never be addressed or not addressed for a very long time, then we'll need to make a permanent remark in our guidance to always use the unminifed script.

Cross-reference: [Revert to minified Google Brotli script in Blazor WASM hosting (dotnet/AspNetCore.Docs #19979)](https://github.com/dotnet/AspNetCore.Docs/issues/19979)

**Comment by guardrex** [comment]
Hello @eustas ... We're cross-linking to this issue (and having to recommend the uncompressed script) in an official Microsoft document. I'd like to relink the compressed script and drop the note to our readers on this. What I might do is go ahead and maintain a fixed copy of the script on our repo until this issue is resolved. Do you know if/when this might be addressed?

**Comment by guardrex** [comment]
@dsnet ... Hello ... May I ask for a contact at Google in charge of this repo? I'm trying to figure out if this issue will be addressed or won't be addressed ... or perhaps addressed at some point in the distant future.

I'm an Aquent LLC contractor working for Microsoft, and we have an important framework compression feature tied to an official Microsoft documentation suggestion to use this Google Brotli script in its compressed form. However, we can't directly link to a broken script here. We may decide to host our own fixed version of this script (under the license, of course, with proper attribution), or we might decide not to use or refer readers to this script at all. It's hard to make a decision on the best course of action given that I can't get an answer here on the triage of this issue.

Can you put me in touch with the right manager at Google who can help? I can be emailed at llatham at the company (Aquent) dot-com if you want to message me offline. Thanks, Luke

**Comment by guardrex** [comment]
@mrpmorris ... There are [updates (google/brotli #852)](https://github.com/google/brotli/pull/852) that apparently will fix this (among other things), but those October updates are in limbo. Microsoft is now seeking to drop the use of this script. We can't depend on unmaintained bits.

**Comment by eustas** [comment]
Sorry, was on  a very long  leave since October. Going to land that update soon.

**Comment by eustas** [comment]
Should be fixed.
