### ISSUE TITLE
Honor CXXFLAGS when building python module

### ISSUE THREAD

**Issue by ryandesign** [google/brotli#851]
Hi. Parts of the brotli python module are written in C++. When compiling that part, the contents of environment variable CXXFLAGS should be passed to the compiler. [setuptools does not support modules written in C++](https://github.com/pypa/setuptools/issues/1192) so you have to hack in support manually (or help the setuptools folks fix it on their end, if you're able).

My preliminary fix is here:

https://github.com/macports/macports-ports/blob/b21a2cbb0d663da9c8c138f8e9346ad1794cf4f3/python/py-brotli/files/CXXFLAGS.patch

It may not be fully correct but it was good enough for me on macOS.

**Comment by animalize** [comment]
I submited a PR https://github.com/google/brotli/pull/855, it remove C++ code, and brings a performance optimization.

**Comment by eustas** [comment]
Looks  cool. Will review and land soon. Thanks!
