### ISSUE TITLE
Using clang-12 / Linux, implicit float conversion error

### ISSUE THREAD

**Issue by blais** [google/brotli#862]
In file included from external/org_brotli/c/enc/block_splitter.c:14:                   
external/org_brotli/c/enc/./bit_cost.h:48:16: error: implicit conversion from 'size_t' (aka 'unsigned long') to 'double' may lose precision [-Werror,-Wimplicit-int-float-conversion]                                                                                                                                                                                      
  if (retval < sum) {                                                                  
             ~ ^~~                                                                     
1 error generated.

**Comment by eustas** [comment]
Fixed
