### ISSUE TITLE
Java source files missing from Github packages, tar.gz and zip, in 1.0.8 and 1.0.9

### ISSUE THREAD

**Issue by wltjr** [google/brotli#863]
Hello, I am unsure what changed, but for some reason the Java sources are no longer included in the source code release assets. Is that intentional? I see the sources still in the repository, but they are not being included for some reason. I am seeking clarification, thank you!

**Comment by eustas** [comment]
Hello. This is intentional. Java sources should be alongside java releases. We hope to make one soon (with the support of "dictionary" decompression).

**Comment by wltjr** [comment]
@eustas Ok, I will look out for the java releases. Thank you!
