### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by crazydef** [google/brotli#875]
Hi,

When including Brotli headers in our own projects, we're experiencing the following compiler warnings in Visual Studio 2019:

brotli\dec\bit_reader.h(27,47): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(110,74): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(119,75): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(108,41): warning C4100: 'n_bits': unreferenced formal parameter
brotli\dec\bit_reader.h(252,39): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(272,39): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(307,39): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(27,47): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(110,74): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(119,75): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(108,41): warning C4100: 'n_bits': unreferenced formal parameter
brotli\dec\bit_reader.h(252,39): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(272,39): warning C4127: conditional expression is constant
brotli\dec\bit_reader.h(307,39): warning C4127: conditional expression is constant
brotli\dec\huffman.c(124,1): warning C4127: conditional expression is constant
brotli\dec\huffman.c(135,1): warning C4127: conditional expression is constant
brotli\dec\decode.c(1174,7): warning C4127: conditional expression is constant

It'd be nice if we didn't see these in the future.  :)

**Comment by eustas** [comment]
`brotli\dec\bit_reader.h(108,41): warning C4100: 'n_bits': unreferenced formal parameter` could be fixed.

Others are just compiler suspicions - it is explicit that we expect "compile-time-constant" conditional expression there, to gain performance on different platforms /  targets. So, you should consider suppressing warning 4127 via command line parameters.

**Comment by crazydef** [comment]
If they're expected, you should be suppressing them.

Taking the following as an example, it would be better (in my opinion) to do something like this anyway:

```
static BROTLI_INLINE uint32_t BitMask(uint32_t n)
{
#if BROTLI_HAS_UBFX
    /* Masking with this expression turns to a single
       "Unsigned Bit Field Extract" UBFX instruction on ARM. */
    return ~((0xFFFFFFFFu) << n);
#elif BROTLI_HAS_IS_CONSTANT
  if (BROTLI_IS_CONSTANT(n))
  {
    return ~((0xFFFFFFFFu) << n);
  }
  else
#endif
  {
    return kBrotliBitMask[n];
  }
}
```

We're not so relaxed about suppressing compiler warnings in our code and it would be nice to not have to constantly play catch up when someone includes your headers in a new part of our code.

**Comment by eustas** [comment]
We also do care about code quality and eliminate warnings.

But here problem is not with `BROTLI_IS_CONSTANT` macro; it is about compiler being picky.
When MSVC adds support for `__builtin_constant_p` the code snippet you have provided will also generate warning, because `BROTLI_IS_CONSTANT(x)` has (instance-wise) constant value.

If we look at warning in `huffman.c` - compiler does not like how `BROTLI_REPEAT` macro  works:
```
#define BROTLI_REPEAT(N, X) {     \
  if ((N & 1) != 0) {X;}          \
  if ((N & 2) != 0) {X; X;}       \
  if ((N & 4) != 0) {X; X; X; X;} \
}
```

I hope we would be able to find a solution that will calm down MSVC...

**Comment by crazydef** [comment]
Microsoft will almost definitely never add support for that.  The Visual Studio compiler is a C++ compiler that happens to have some limited support for older versions of C.  In C++ there are better, standard ways to do this.

**Comment by eustas** [comment]
`BROTLI_REPEAT` was unwrapped. Will check soon what remaining warnings we have and fix them.

**Comment by eustas** [comment]
There is no extra formatting in dictionary to make it dense. The original dictionary looks like:
```
  "diamond", "use the", "airline", "end -->", ").attr(", "readers", "hosting",
  "#ffffff", "realize", "Vincent", "signals", " src=\"/", "Product", "despite",
  "diverse", "telling", "Public ", "held in", "Joseph ", "theatre", "affects",
  "<style>", "a large", "doesn't", "later, ", "Element", "favicon", "creator",
  "Hungary", "Airport", "see the", "so that", "Michael", "Systems", "Program",
  "s, and ", " width=", "e&quot;", "trading", "left\">\n", "persons", "Golden ",
  "Affairs", "grammar", "forming", "destroy", "idea of", "case of", "oldest ",
  "this is", ".src = ", "cartoon", "registr", "Commons", "Muslims", "What is",
  "in many", "marking", "reveals", "Indeed,", "equally", "/show_a", "outdoor",
  "escape(", "Austria", "genetic", "system,", "In the ", "sitting", "He also",
  "Islands", "Academy", "\n\t\t<!--", "Daniel ", "binding", "block\">",
  "imposed", "utilize", "Abraham", "(except", "{width:", "putting", ").html(",
  "|| [];\n", "DATA[ *", "kitchen", "mounted", "actual ", "dialect", "mainly ",
  "_blank'", "install", "experts", "if(type", "It also", "&copy; ", "\">Terms",
  "born in", "Options", "eastern", "talking", "concern", "gained ", "ongoing",
  "justify", "critics", "factory", "its own", "assault", "invited", "lasting",
  "his own", "href=\"/", "\" rel=\"", "develop", "concert", "diagram",
  "dollars", "cluster", "php?id=", "alcohol", ");})();", "using a", "><span>",
```

No need to worry about the "scary" character combinations.
