### ISSUE TITLE
go - cbrotli - fatal error: brotli/decode.h: No such file or directory

### ISSUE THREAD

**Issue by true-zero** [google/brotli#890]
Cannot install Golang cbrotli due to a missing file.

`cbrotli\reader.go:12:10: fatal error: brotli/decode.h: No such file or directory`

**Comment by micheartin** [comment]
To use `cbrotli` in your Golang project, before you should compile the C implementation in your local machine. See the [README.md](https://github.com/google/brotli#build-instructions) for build instructions. See also <https://stackoverflow.com/q/47233208#53095243>.
