### ISSUE TITLE
There is no CRC in the format and there is no way to detect corruption

### ISSUE THREAD

**Issue by eshkinkot** [google/brotli#922]
```
git clone https://github.com/google/brotli.git
cd brotli/
make

echo 'this is test file for check compression checksums' > file
bin/brotli file
cp file.br file-corrupt.br
echo -ne '\xA6' | dd bs=1 conv=notrunc seek=$((0x18)) of=file-corrupt.br
```

```
$ hd file.br; hd file-corrupt.br
00000000  a1 88 01 00 2f b0 01 e7  0b ed 32 4e 7d 0f 52 88  |..../.....2N}.R.|
00000010  2a c0 68 10 2a 86 63 e7  b6 30 5f 4b 50 3e b3 40  |*.h.*.c..0_KP>.@|
00000020  bc 08                                             |..|
00000022
00000000  a1 88 01 00 2f b0 01 e7  0b ed 32 4e 7d 0f 52 88  |..../.....2N}.R.|
00000010  2a c0 68 10 2a 86 63 e7  a6 30 5f 4b 50 3e b3 40  |*.h.*.c..0_KP>.@|
00000020  bc 08                                             |..|
00000022
$ bin/brotli -v -t file-corrupt.br; echo $?
Decompressed [file-corrupt.br]: 34 B -> 50 B in 0.00 sec
0
$ bin/brotli -v -d file-corrupt.br; echo $?
Decompressed [file-corrupt.br]: 34 B -> 50 B in 0.00 sec
0
$ hd file; hd file-corrupt
00000000  74 68 69 73 20 69 73 20  74 65 73 74 20 66 69 6c  |this is test fil|
00000010  65 20 66 6f 72 20 63 68  65 63 6b 20 63 6f 6d 70  |e for check comp|
00000020  72 65 73 73 69 6f 6e 20  63 68 65 63 6b 73 75 6d  |ression checksum|
00000030  73 0a                                             |s.|
00000032
00000000  74 68 69 73 20 69 73 20  0a 65 73 74 20 66 69 6c  |this is .est fil|
00000010  65 20 66 6f 72 20 63 68  65 63 6b 20 63 6f 6d 70  |e for check comp|
00000020  72 65 73 73 69 6f 6e 20  63 68 65 63 6b 73 75 6d  |ression checksum|
00000030  73 0a                                             |s.|
00000032
```

![vbindiff file file-corrupt](https://user-images.githubusercontent.com/69589/131365671-1abb7e40-53da-442a-b4c2-50902cc8da6c.png)

**Comment by eustas** [comment]
That is correct. Brotli itself is a stream format. It lacks features like CRC, multiple entries, uncompressed size info, rewind, etc.
Currently one could add custom "framing" to address that. Later [Brotli Framing](https://datatracker.ietf.org/doc/html/draft-vandevenne-shared-brotli-format-04) could be an out-of-the-box solution

**Comment by eustas** [comment]
Alternatively one could also use [Rigeli](https://github.com/google/riegeli) as framing format.

**Comment by eustas** [comment]
Sure, will mention in README.
However, the scope of possible damage is very small: only uncompressible data is dumped as is. For entropy coded data (compressible) the probability that corrupted data is not noticed is very small. I could prepare a script to calculate it.

**Comment by eustas** [comment]
Resolved in a8f581

**Comment by Artoria2e5** [comment]
Brotli running without framing is hurting its chances at replacing gzip in the tar.gz usecase. At least this is the story on the bsdtar (libarchive) side https://github.com/libarchive/libarchive/issues/1238#issuecomment-529746683: it does a very Unix approach to format detection using no file name but just contents, but brotli has no magic number for it to work with.
