### ISSUE TITLE
Getting errors in console when loading Blazor app.

### ISSUE THREAD

**Issue by Sellorio** [google/brotli#937]
Errors include (and this is not a joke):

```
(52) Uncaught (in promise) Exuberant nibble
Uncaught (in promise) Corrupted Huffman code histogram
Streaming compilation failed. Falling back to ArrayBuffer instance
Corrupted padding bits
(2) Uncaught (in promise) Corrupted padding bits
```

This is also somewhat inconsistently happening since it works fine on 1 computer and everyone else so far as this issue.

**Comment by eustas** [comment]
Hello. Could you provide more context?
Is Blazor using C# brotli implementation? I believe that one wasn't regenerated for a while...

**Comment by eustas** [comment]
If it  is based on WASMified brotli, then it would be nice to see at failing streams and binaries. Perhaps problem occur in WASM engine itself...

**Comment by fortunacodes** [comment]
I have the same problem now, no idea what's going on. 

I just followed what Microsoft says here: https://learn.microsoft.com/en-us/aspnet/core/blazor/host-and-deploy/webassembly?view=aspnetcore-6.0

I am hosting a Static Web App on Azure.

**Comment by eustas** [comment]
If you set network throttling in devtools, does it reproduce more or less frequently?
