### ISSUE TITLE
How to make brotli works in k8s with official nginx helm

### ISSUE THREAD

**Issue by DmitriyEsin** [google/brotli#943]
Hi guys!
Does anyone do brotli works in Kubernetes?

**Comment by DmitriyEsin** [comment]
when i try to patch my ingress I got
`Error: exit status 1
2021/12/15 14:38:28 [warn] 17936#17936: the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx-cfg126647862:143
nginx: [warn] the "http2_max_field_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx-cfg126647862:143
2021/12/15 14:38:28 [warn] 17936#17936: the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx-cfg126647862:144
nginx: [warn] the "http2_max_header_size" directive is obsolete, use the "large_client_header_buffers" directive instead in /tmp/nginx-cfg126647862:144
2021/12/15 14:38:28 [warn] 17936#17936: the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /tmp/nginx-cfg126647862:145
nginx: [warn] the "http2_max_requests" directive is obsolete, use the "keepalive_requests" directive instead in /tmp/nginx-cfg126647862:145
2021/12/15 14:38:28 [emerg] 17936#17936: unknown directive "brotli" in /tmp/nginx-cfg126647862:877
nginx: [emerg] unknown directive "brotli" in /tmp/nginx-cfg126647862:877
nginx: configuration file /tmp/nginx-cfg126647862 test failed`

**Comment by eustas** [comment]
Hello. I believe it is ngx_brotli problem, not brotli itself.

**Comment by DmitriyEsin** [comment]
Okay, thank you for answer.
