### ISSUE TITLE
best practice on java platform

### ISSUE THREAD

**Issue by lixuemuyangfeng** [google/brotli#948]
I'm a rookie here and want to learn about brotli's best practices on the Java platform
i used to use https://github.com/nixxcode/jvm-brotli ,but does not work due to the version of gcc...
now i hava ask here.
Is there any Experienced Bro who can help ?

**Comment by hyperxpro** [comment]
Try this instead: https://github.com/hyperxpro/Brotli4j

**Comment by slandelle** [comment]
Should be closed
