### ISSUE TITLE
Request for wheel for musllinux (Alpine)

### ISSUE THREAD

**Issue by tgross35** [google/brotli#949]
Since PEP 656 got adopted, it is now possible to build wheels for musllinux and distribute them on pypi, which makes them installable on Alpine linux (docker) without any extra installs. Could the maintainers of brotli consider shipping a musl wheel?

As an example - Gevent recently added a musllinux build, workflow here https://github.com/gevent/gevent/blob/master/.github/workflows/ci.yml

**Comment by anthrotype** [comment]
We build the wheels on https://github.com/google/brotli-wheels
Would you like to work on a PR?

**Comment by anthrotype** [comment]
looks like the latest cibuildwheel already builds musllinux wheels automatically. I just pushed an empty commit to trigger the google/brotli-wheels CI and I can see those being built. 
https://github.com/google/brotli-wheels/runs/4919842056
I think i'm going to just download them from github CI artifacts and upload them manually to PyPI. Once a new brotli release is made, they will be automatically uploaded along with the rest of the wheels.

**Comment by anthrotype** [comment]
I just uploaded to PyPI musllinux wheels for cpython 3.6 to 3.10, for x86_64, i686 and aarch64 architectures, as built by cibuildwheel in https://github.com/google/brotli-wheels/runs/4919842056
Let me know if that suits you or you need more.

**Comment by tgross35** [comment]
@anthrotype Excellent, thank you! Works great, quite a nice speed boost to docker builds.
