### ISSUE TITLE
Version header is not exported

### ISSUE THREAD

**Issue by tawmoto** [google/brotli#950]
Hi, 
I am using Brotli as a static library, which I store it on Artifactory. When I download it from Artifactory via CMake, I need to find its version, but it seems that I cannot, because the version header is not exported. The only exported headers are `decode.h, encode.h, types.h and port.h`

https://github.com/google/brotli/blob/master/c/common/version.h#L17

Is there any way to read the version from the "package" via CMake?
Thanks

**Comment by znzjugod** [comment]
try to add version.h in brotli/c/include/brotli

**Comment by eustas** [comment]
Dupe of #773
