### ISSUE TITLE
gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':

### ISSUE THREAD

**Issue by 308066400** [google/brotli#959]
gcc_libinit_windows.c:58:19: error: implicit declaration of function '_beginthread'; did you mean 'OpenThread'? [-Werror=implicit-function-declaration]
   58 |         thandle = _beginthread(func, 0, arg);
      |                   ^~~~~~~~~~~~
      |                   OpenThread
cc1: all warnings being treated as errors

**Comment by eustas** [comment]
But `gcc_libinit_windows.c` is not in brotli?
