### ISSUE TITLE
Autotools build system does not set OS_ defines

### ISSUE THREAD

**Issue by ryandesign** [google/brotli#963]
The cmake build system sets some custom defines for various OS types in CMakeLists.txt

```
if(${CMAKE_SYSTEM_NAME} MATCHES "Linux")
  add_definitions(-DOS_LINUX)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "FreeBSD")
  add_definitions(-DOS_FREEBSD)
elseif(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
  add_definitions(-DOS_MACOSX)
endif()
```

The undocumented autotools build system does not. Perhaps it should?

**Comment by eustas** [comment]
TODO: add the following definitions to Bazel / naked make / autotools:
 - [ ] `OS_LINUX`
 - [ ] `OS_FREEBSD`
 - [ ] `OS_MACOSX`
 - [ ] `BROTLI_HAVE_LOG2`
