### ISSUE TITLE
Brotli c code is applied to the iOS swift project, and the best compression level is also used. The 39M mac platform can be compressed to 3.2M, but iOS can only be compressed to 15.4M

### ISSUE THREAD

**Issue by ZhengXiuQun** [google/brotli#972]
In the ios project, I need to use Brotli to compress the data, but what makes me wonder is that the same problem, I can compress the data to 3.2M on the mac platform, but why on the ios device, the same level 11 compression is used, I can only compress it into 15.4M.

**Comment by eustas** [comment]
Hello. Could you add more details, please.
Ideally, a tiny repro project.
