### ISSUE TITLE
Execute brotli -v will generate a series of files ending with .br

### ISSUE THREAD

**Issue by znzjugod** [google/brotli#973]
According to the prompt, -v should only display verbose mode. However, after -v is run, an extra file is generated in the folder and the compressed file is compressed continuously.
results as follows:
![image](https://user-images.githubusercontent.com/106044623/183658008-4168950a-a8c4-45bc-b5b1-513c2a36706b.png)

**Comment by eustas** [comment]
Verbose **mode** means that more information will be printed.
If neither of compress / decompress / test action is specified, then default action is chosen: compress for `brotli` binary, and decompress for `unbrotli`.
