### ISSUE TITLE
include Windows executable

### ISSUE THREAD

**Issue by garretwilson** [google/brotli#983]
Please include a Windows executable in the distribution here on GitHub. It appears that the last version to include a Windows executable was [v1.0.4](https://github.com/google/brotli/releases/tag/v1.0.4), four years ago. It is my understanding from your readme that this version contained vulnerabilities.

**Comment by btx638** [comment]
Alternate Brotli DLL build for Visual Studio  https://github.com/diovoemor/winbro

**Comment by flawrist** [comment]
Windows 7 SP1 x64, brotli 1.2.0 works like a charm, thank you!
